### ISSUE TITLE
Log in without chat

### ISSUE THREAD

**Issue by harthwell** [nextcloud/jsxc.nextcloud#100]
Log in without chat appears on the log-in page whenever I install JSXC. Is there any way to remove this? Since even after I logged-out in my account, and when I go back to log-in, I just click log-in without chat and voila, it enters the home page without encoding the password.

**Comment by sualko** [comment]
Sorry, but I don't have a glue what you are talking about. Can you explain it in more detail?

**Comment by harthwell** [comment]
I installed JSXC. Now, whenever I log-in, I see the "log-in without chat" link just below the login. Check this out - https://imgur.com/a/LXM1N. 

Can this be removed? It is because whenever I logged-out, and when I try to log-in again, I just clicked that link and I can access Nextcloud even without putting my username and password,

**Comment by sualko** [comment]
> It is because whenever I logged-out, and when I try to log-in again, I just clicked that link and I can access Nextcloud even without putting my username and password,

You can log in to Nextcloud without a password?

**Comment by harthwell** [comment]
Yeah. Even if I logged-out already.

**Comment by harthwell** [comment]
I guess it's because of Chrome? I tried to log-in in IE it works fine there.

**Comment by sualko** [comment]
Did you use the store password function from Chrome?

**Comment by sualko** [comment]
Sorry I can't reproduce your issue nor imagine how this should work. Due to inactivity, I close this issue.

**Comment by elvisef** [comment]
I have a similar issue, I want to remove these login buttons, but settings for this is nowhere.
How to remove these ?
![29042020_09:44:29_Zaznaczenie](https://user-images.githubusercontent.com/25976749/80572502-afa8df80-89fe-11ea-8a74-d8bd182e9888.png)
