### ISSUE TITLE
Can't connect to chat while muc is activated

### ISSUE THREAD

**Issue by t4nki** [nextcloud/jsxc.nextcloud#101]
Hi,

I'm using prosody configured with working chatrooms
If I use another client (on my phone for example) I can connect and use chatrooms normally.

But if I try to login to jsxc on my nexctloud install, it does nothing.

My prosody server and my nextcloud server are on the same host.
Please note that when I disable muc in my prosody config, login on jsxc works fine and communication is possible between various clients

Thanks for any help you can provide

**Comment by sualko** [comment]
Please [enable debugging](https://github.com/jsxc/jsxc/wiki/Debugging) and post your js console log.

**Comment by t4nki** [comment]
here's what I get

`State changed to ESTABLISHING
jsxc.js:183:9
New connection
jsxc.js:183:9
CONNECTING: null
jsxc.js:183:9
> 
<body rid="2904207344" xmlns="http://jabber.org/protocol/httpbind" to="centos.lan" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh">
jsxc.js:1261:12
< 
<body xmlns:stream="http://etherx.jabber.org/streams" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh" ver="1.6" inactivity="60" requests="2" polling="5" secure="true" hold="1" from="centos.lan" authid="53738356-9dfc-44d9-b763-2030aa4af859" wait="60" sid="53738356-9dfc-44d9-b763-2030aa4af859" xmlns="http://jabber.org/protocol/httpbind">
jsxc.js:1258:12
> 
<body rid="2904207345" xmlns="http://jabber.org/protocol/httpbind" sid="53738356-9dfc-44d9-b763-2030aa4af859">
jsxc.js:1261:1`

let me know if it's okay or if you need more informations

**Comment by t4nki** [comment]
alright
I have completely redone my prosody config and it appears it's a certificate problem
 if I chose :
 c2s_require_encryption = true
authentication does not work, 
whereas, if i chose :
c2s_require_encryption = false
connection to my prosody server via jsxc with muc enabled works flawlessly
Hence my guess is that it is a certificate problem into my prosody.cfg.lua config file
thanks for your time anyway
cheers
