### ISSUE TITLE
OC_USER_IMAP Backend after update to 3.4.0 NC13

### ISSUE THREAD

**Issue by fl0w1** [nextcloud/jsxc.nextcloud#104]
Hey,

after the last update to version 3.4.0 users with oc_user_imap backend cannot
longer login. Right after logging in the Nextcloud 13 Server responds with internal Server Error.

Server details:
 Nextcloud 13.0.2
 JavaScript XMPP Chat 3.4.0
 Browser: Multiple Browsers tested (with and without addons)

Error Message from NextCloud Log:
{"reqId":"WwfEbMtviJtFPDPNTeikpAAAAFI","level":3,"time":"2018-05-25T10:08:13+02:00","remoteAddr":"<ip here>","user":"user@example.org","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OC_User_IMAP::getBackendName()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/html\\\/apps\\\/ojsxc\\\/appinfo\\\/application.php(284): OCA\\\\OJSXC\\\\AppInfo\\\\Application::convertToRealUID('user...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/html\\\/apps\\\/ojsxc\\\/appinfo\\\/routes.php(8): OCA\\\\OJSXC\\\\AppInfo\\\\Application->__construct()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(351): include_once('\\\/var\\\/www\\\/cloud....')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(151): OC\\\\Route\\\\Router->requireRouteFile('\\\/var\\\/www\\\/cloud....', 'ojsxc')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(268): OC\\\\Route\\\\Router->loadRoutes()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/html\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/html\\\/index.php(37): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/html\\\/apps\\\/ojsxc\\\/appinfo\\\/application.php\",\"Line\":366}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}

The problem was solved by disabling the ojsxc app.

Cheers,

Florian

**Comment by sualko** [comment]
Do you use the internal chat backend?

**Comment by fl0w1** [comment]
Yes, I do.Am 25.05.2018 6:28 nachm. schrieb Klaus <notifications@github.com>:Do you use the internal chat backend?

**Comment by MarcelWaldvogel** [comment]
According to my sources ;-), every call of getBackendName in Nextcloud itself looks like that:
* https://github.com/nextcloud/server/blob/master/lib/private/User/Manager.php#L371
* https://github.com/nextcloud/server/blob/master/apps/files_versions/lib/Command/CleanUp.php#L79
* …

**Comment by Glandos** [comment]
The patch works for me, with the IMAP backend. Thanks.
