### ISSUE TITLE
Registering a new managed server fails in Nextcloud

### ISSUE THREAD

**Issue by khassad** [nextcloud/jsxc.nextcloud#106]
* jsxc 3.4.0
* nextcloud 13.0.2.1
* How to reproduce : In Nextcloud app, set to managed server, just click on Register and wait 5 secs.

Error is : 
    Could not perform internal changes part 2.

The request id uzb1FyfW9L1TcnYjSLMU.
I tried several times, this is only latest request id, I can provide more if needed.

**Comment by MarcelWaldvogel** [comment]
Thanks for reporting. Yes, indeed, when we had to change to a different server on short notice due to a problem with our service provider last week, something went wrong. I have fixed this now. Could you please try again?

Sorry for the inconvenience.

**Comment by MarcelWaldvogel** [comment]
(One of the request IDs is good enough, BTW)

**Comment by khassad** [comment]
All good now, thanks Marcel !
