### ISSUE TITLE
Error while running background job (OCP\AutoloadNot AllowedException): Autoload path not allowed

### ISSUE THREAD

**Issue by samtygier** [nextcloud/jsxc.nextcloud#109]
I originally reported this against the server, but I think it is due to the jsxc app, so linking here nextcloud/server/issues/10658

**Comment by sualko** [comment]
Sorry, that you didn't get any response. I will look at it asap.

**Comment by sualko** [comment]
I have no clue why you are getting this message and the error log is also not that verbose :cry:. I'm sorry, but currently I can't help you.

**Comment by Luticus** [comment]
I have some experience with trying to use lurch with pidgin and even audium on mac and in either case my results were not good.  This could easily be an issue with lurch and not with jsxc.  I use the conversations app on my phone and pidgin/lurch doesn't seem to like it.  I would test between conversations and jsxc and see if you get better results.  I'll try to test all 3 out, maybe later today.  I was trying to wait for the stable release but I do have a test server so maybe I could set something up there and help that way.  Anyhow, just my 2 cents on the subject.
