### ISSUE TITLE
Missing chat icon on the top panel in NC14.0.3

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/jsxc.nextcloud#111]
Nextcloud server 14.0.3
ubuntu 16.04.5
php 7.0.32
JavaScript XMPP Chat 3.4.2

Disappeared chat icon on the top toolbar, the application "files" and "bookmarks" after upgrading to NC14.0.3

**Comment by sualko** [comment]
>  the application "files" and "bookmarks" after upgrading to NC14.0.3

What do you mean by this? Can you post a screenshot of the top right corner of your nc?

**Comment by lvarnava** [comment]
![2018-10-24_12-40-30](https://user-images.githubusercontent.com/32108411/47421980-5c5f2c80-d78a-11e8-9f6f-f62c1906d0a7.png)
![2018-10-24_12-40-53](https://user-images.githubusercontent.com/32108411/47421992-5f5a1d00-d78a-11e8-8ab8-a30aaa8196cf.png)

**Comment by sualko** [comment]
Do you use any search app? Because the magnifier doesn't look like from the core. We place your icon before the search icon and if it is replaced this will probably fail.

**Comment by lvarnava** [comment]
![2018-10-24_15-53-48](https://user-images.githubusercontent.com/32108411/47431665-182d5580-d7a5-11e8-9875-a2b87ff7acb4.png)

**Comment by lvarnava** [comment]
When the "fulltextsearch" is disabled then the icon appears!
And the application "bookmarks" is running, which was previously blocked!

**Comment by sualko** [comment]
Can you try to replace https://github.com/nextcloud/jsxc.nextcloud/blob/9b1971433103978fdd3fd620fb451bd891351247/js/ojsxc.js#L115

with the following:

```
if ($('#header form.searchbox').length) {
     $('#header form.searchbox').after(div);
} else {
     $('#fulltextsearch').after(div);
}
```

**Comment by lvarnava** [comment]
I tried. With "bookmarks" it all worked.
With "Files" Nothing has changed.

**Comment by lvarnava** [comment]
but after indexing the bookmarks instead of the usual search, a full-text search icon appeared, and the bookmarks became inaccessible.

**Comment by sualko** [comment]
> the bookmarks became inaccessible

but how is this related to JSXC? Maybe you can post another screenshot.

**Comment by lvarnava** [comment]
![2018-11-21_20-13-48](https://user-images.githubusercontent.com/32108411/48857529-25e8f180-edca-11e8-8e7d-e42dc5b9e072.png)

**Comment by lvarnava** [comment]
I think this is a glitch application "Full text search - Bookmarks".

**Comment by lvarnava** [comment]
when i turned "Full text search - Bookmarks" off
![2018-11-21_20-21-29](https://user-images.githubusercontent.com/32108411/48857952-39e12300-edcb-11e8-94a0-8169a32777b4.png)
