### ISSUE TITLE
Show mail address as JID in personal settings when "Prefer mail address to loginName@xmppDomain" is set in admin settings

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/jsxc.nextcloud#117]
When "Prefer mail address to loginName@xmppDomain" is set in admin settings the shown JID should usually match the mail address and should be shown in the personal preferences instead.

**Comment by DanScharon** [comment]
*cough*

**Comment by sualko** [comment]
_cough_ there was one, no two, release candidates....

**Comment by DanScharon** [comment]
@sualko my pr is from Feb 11 ;) but yeah, not compatible anymore with 4.0

**Comment by sualko** [comment]
> not compatible anymore with 4.0

why?

**Comment by DanScharon** [comment]
forgot to add the check for 1 and '1' in addition to true and 'true' 🙈 
I will prepare another pr...

**Comment by DanScharon** [comment]
ok, pr #133 should work now
