### ISSUE TITLE
Connection fails

### ISSUE THREAD

**Issue by pojntfx** [nextcloud/jsxc.nextcloud#118]
First off all: Thanks so much for this app. It truly is amazing.
I've just tried to use the managed XMPP server and it's not working on the 2 Nextclouds I've tried it on. Here are the logs (fresh Nextcloud 14.03 installation):

```plaintext
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
State changed to INITIATING jsxc.js:184:9
Try to relogin jsxc.js:184:9
Logout was forced or I found no valid jid jsxc.js:184:9
State changed to SUSPEND jsxc.js:184:9
[WARN] Unable to create user prefix
jsxc.js:184:9
[WARN] Unable to create user prefix jsxc.js:184:9
Try to relogin jsxc.js:184:9
Logout was forced or I found no valid jid jsxc.js:184:9
[WARN] Unable to create user prefix
```
Does somebody know what's going on here?

**Comment by pojntfx** [comment]
Just tried to login with `Conversations`. It's also not working.

**Comment by MarcelWaldvogel** [comment]
Thanks for the nice words, we really appreciate them!

Sorry for the trouble, one permission on the managed server was set too tight, so the new configuration could not be activated. It should work again since about an hour ago.

**Comment by MarcelWaldvogel** [comment]
BTW: The name you got for the second managed server registration is rather long. If you want to, I can delete it and you can re-register; you will then get a shorter name. (Your hosters did not add their domain name to the [PSL](https://github.com/publicsuffix/list); I have added them manually to our list.)

**Comment by pojntfx** [comment]
It's working now! Thanks so much for looking into it.
