### ISSUE TITLE
Font color using dark theme

### ISSUE THREAD

**Issue by mamatt** [nextcloud/jsxc.nextcloud#122]
When activating the dark theme in Nextcloud the font color switch to silver grey.
This is the normal behavior.

In the chat windows the text is not really visible as the  background is light green or light blue !
![Capture Chat UNCloud](https://user-images.githubusercontent.com/6310611/55148315-3fb78e00-5148-11e9-9e9f-5e84806fc5d2.PNG)

**Comment by sualko** [comment]
Thanks for the report. We will try to fix it in the next release.

**Comment by ostasevych** [comment]
Still not fixed...
