### ISSUE TITLE
Pictures/Files will not upload when sending

### ISSUE THREAD

**Issue by Luticus** [nextcloud/jsxc.nextcloud#123]
When I attempt to send a picture in ojsxc I get this error in the java console: 
[WARN] error while uploading file to https://<host@domain.com>:<port>/upload/e0c60bd9791647a2d85ed89f1017457af28437fa/jzryyBNAhAVD1Drmo8xFveIkor4SnIWTKPCOkUhH/Favicon.png

This happens on both 3.x and 4 versions of the chat client.  I can confirm that uploads otherwise work on the server via pidgin, adium, and conversations.  I'm using the newest Firefox.  The server is using NC16, but this happened on 15 as well.  The server os is Debian 9, and the clients are Debian 9, macOS, Windows 10 all latest stable versions.  This also happens in Google Chrome

**Comment by MarcelWaldvogel** [comment]
Which XMPP server do you use?

Does your XMPP server's HTTP Upload component send the CORS headers? https://github.com/jsxc/jsxc/wiki/File-transfer

**Comment by sualko** [comment]
Plus if the host (domain or port) differs from your nextcloud host, you have to add the http upload host to the custom csp section of your ojsxc admin config.

**Comment by Luticus** [comment]
I use ejabberd from debian backports, don't know the version off hand.  My apache server proxys the bosh protocol.  So I use /chat/ as my url as I've always done.  I know the images thing used to work and I'm not sure what version it stopped working on.  If there's a setting I should change that you guys know of, I'll all about doing that.  :). I can definitly look into the CORS headers and the custom csp thing, though It was my understanding that if you proxy it you don't need to use custom csp.

**Comment by Luticus** [comment]
Ok, so I have ironed out the issue.  It was technically my fault, but it was not intuitive to fix.

My situation is I have one domain, well call it example.com.  I have a cloud server hosting NC16 (cloud.example.com) and an xmpp server (xmpp.example.com) hosting ejabberd.  I want my xmpp users to all have @example.com, NOT @xmpp.example.com.  The main problem I ran into was the ports.  The /upload in ejabberd want's to listen on 5443, but that's unacceptable because work networks, etc may block that port causing problems.

Here's what I suggest for new people who want to do this:
configure ejabberd.yml's mod_http_upload section like this
mod_http_upload:
    docroot: "/ejabberd/upload"
    put_url: "https://example.com:443/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
      "Access-Control-Allow-Headers": "Content-Type"
*note that mod_http_upload is still going to listen on *5443*!  Do not change that, only the put url.

Then in apache in your virtual host, create a proxy like so:
ProxyPass /upload https://example.com:5443/upload
ProxyPassReverse /upload https://example.com:5443/upload

This should proxy the traffic though the cloud server and to the ejabberd server at the expected port (5443).  

The issue can be closed.

**Comment by madmath03** [comment]
I'm exactly in the same situation as @Luticus described (users @example.com, NC @cloud and Ejabberd @xmpp), but I'm wondering something...

I've seen in [ejabberd doc ](https://docs.ejabberd.im/admin/configuration/#mod-http-upload) that `mod_http_upload` is usually accessed at upload.example.com, but it seems that JSXC just contact example.com.

Shouldn't that mean that there is an error in the app or JSXC and we should be able to override the default upload URL ?
I feel like being able to override the upload URL to a subdomain would prevent this unintuitive proxy hack.

**Comment by MarcelWaldvogel** [comment]
JSXC asks the XMPP server for its upload URL and uses that. Could it be that this is misconfigured?

**Comment by madmath03** [comment]
That's a good question.

I thought that for a time too, so I forced the `host` of `mod_http_upload` but no change : JSXC still tries to to upload at `example.com` instead of `upload.example.com` so I thought JSXC was simply using the xmpp domain.

How does JSXC retrieves the upload URL ? How can I check it ?

**Comment by madmath03** [comment]
Ok my bad, found out...
I misunderstood some of the ejabberd doc and thought the `host` property of `mod_http_upload` would replace the `@HOST@ ` in the URLs but I was wrong...

Anyway, for those who also encounter this, here is my ejabberd config that worked : 
```
  mod_http_upload:
    host: "upload.@HOST@"
    put_url: "https://upload.@HOST@:443/upload"
    get_url: "https://upload.@HOST@:443/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, POST, PUT, DELETE"
      "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With"
```

And there is a Nginx proxying from 443 to 5443.
