### ISSUE TITLE
The list with rooms is empty

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/jsxc.nextcloud#125]
When I try to join the chat I cannot see the list of rooms, previously created by me or any other users in the drop-down list of the field Rooms. The list is empty. 
However, I may join the chat room by entering the name of the room exactly in the field Room
Prosody on Nextcloud with muc.
![Screenshot_1](https://user-images.githubusercontent.com/5199030/65634569-2c965580-dfe7-11e9-92db-19fee64d2ce9.png)

**Comment by sualko** [comment]
Do you have any errors in your js console? How is your room configuration? Is it working with other clients?

**Comment by sualko** [comment]
duplicate of jsxc/jsxc#830
