### ISSUE TITLE
4.0.0rc1 does not work correctly with totp authentication

### ISSUE THREAD

**Issue by Luticus** [nextcloud/jsxc.nextcloud#126]
I'm using Nextcloud 18.0.1 and the latest release 4.0.0rc1 of jsxc.  After entering the user name and password on my server I'm directed to the second factor page for one time passwords or yubikeys, unfortunately the chat side bar is visible and can auto login at this point thus bypassing two factor authentication for web chat.  I think it would be preferred that chat was delayed until after the second factor has been authenticated.  Even if you disable auto login for jsxc, the side bar sill pops out and makes itself visible, it also provides a login mechanism in the sidebar that would allow the second factor to be bypassed for chat.

**Comment by sualko** [comment]
I close this in favor of jsxc/jsxc#885
