### ISSUE TITLE
Unable to verify release v4.0.0-rc.1 with gpg

### ISSUE THREAD

**Issue by resoli** [nextcloud/jsxc.nextcloud#127]
```
$ LANG=en_EN gpg --verify ojsxc-4.0.0-rc.1.tar.gz.sig ojsxc-4.0.0-rc.1.tar.gz
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.

```

**Comment by sualko** [comment]
This is a special Nextcloud signature. Sorry for the confusion. I should maybe change the suffix and leave the issue therefore open.

**Comment by resoli** [comment]
The release files scheme is the same in jsxc, and gpg verification is working there. I agree on the suffix change, but maintaining the gpg signature with .sig (or better, making it armored with .asc suffix) would be really nice.
Congratulations for your work, looking for stable v4 with OMEMO!

**Comment by sualko** [comment]
> or even better, making it armored with .asc suffix

What do you mean by that? As far as I know asc files contain only pgp public keys. If you are looking for my key, you find it on the keyserver or on [keybase](https://keybase.io/sualko).

> Congratulations for your work, looking forward for stable v4 with OMEMO!

I too :wink:. Thanks for the kind words. Hopefully I find some time to fix the last bugs and release it.

**Comment by resoli** [comment]
If you want a detached signature:
Sign, armored and detached:
`echo ciao | gpg --sign --armor --detached --output ciao.asc`

Verify:
```
$ echo ciao > ciao 
$LANG=en_EN gpg --verify ciao.asc ciao
gpg: Signature made Thu Oct 17 09:41:05 2019 CEST
gpg:                using RSA key 7B6D8BF39245FCE6DC33A9B39995A4DAEC5765CF
gpg: Good signature from "Roberto Resoli <roberto@resolutions.it>" [ultimate]
```

**Comment by resoli** [comment]
> > Congratulations for your work, looking forward for stable v4 with OMEMO!
> 
> I too ;-) . Thanks for the kind words. Hopefully I find some time to fix the last bugs and release it.

Really you deserve that. If you can add a proper signature I will be glad to test the RC as well!

**Comment by sualko** [comment]
> No, you can "clearsign" or "armor" when signing:

I was just talking about the suffix. I saw only `.sig` files for signatures and `.asc` for keys. Also my nautilus extension creates `.sig` files. Therefore I asked why you prefer a `.asc` file as signature file.

> If you can add a proper signature I will be glad to test the RC as well!

That should be no problem. Will change the sig file to a proper pgp signature and add the Nextcloud signature as ncsig.

**Comment by sualko** [comment]
> Therefore I asked why you prefer a .asc file as signature file.

Ah ok, it's really only related to the format. Sorry for the confusion and thanks that I learned something new.
