### ISSUE TITLE
Nextcloud, jsxc and xcauth

### ISSUE THREAD

**Issue by nkrupp** [nextcloud/jsxc.nextcloud#129]
Dear all,

when using xcauth together with jsxc I have the problem that only every second login is successful. When pressing the login button it will freeze at "logging in". However, after reloading the page and trying to login again everything is fine. I found this exception in the javascript log:

main.js?v=496616e2-15:396 JQMIGRATE: Migrate is installed, version 1.4.1
main.js?v=496616e2-15:1095 oc_config is deprecated: use OC.config instead
He @ main.js?v=496616e2-15:1095
main.js?v=496616e2-15:1095 oc_appswebroots is deprecated: use OC.appswebroots instead
He @ main.js?v=496616e2-15:1095
main.js?v=496616e2-15:1095 oc_config is deprecated: use OC.config instead
He @ main.js?v=496616e2-15:1095
main.js?v=496616e2-15:1095 oc_appswebroots is deprecated: use OC.appswebroots instead
He @ main.js?v=496616e2-15:1095
jsxc.min.js?v=496616e2-15:1 State changed to INITIATING
jsxc.min.js?v=496616e2-15:1 Try to relogin
jsxc.min.js?v=496616e2-15:1 Logout was forced or I found no valid jid
jsxc.min.js?v=496616e2-15:1 State changed to TRYTOINTERCEPT
jsxc.min.js?v=496616e2-15:1 State changed to INTERCEPTED
jsxc.min.js?v=496616e2-15:1 Variable serverType doesn't exist. It was created.
jsxc.min.js?v=496616e2-15:1 Variable loginForm doesn't exist. It was created.
jsxc.min.js?v=496616e2-15:1 Uncaught TypeError: Converting circular structure to JSON
--> starting at object with constructor 's'
--- property '_renderProxy' closes the circle
at JSON.stringify ()
at Object.setItem (jsxc.min.js?v=496616e2-15:1)
at Object.updateItem (jsxc.min.js?v=496616e2-15:1)
at Object.jsxc.options.set (jsxc.min.js?v=496616e2-15:1)
at Object. (jsxc.min.js?v=496616e2-15:1)
at Function.each (main.js?v=496616e2-15:14)
at Object._prepareLogin (jsxc.min.js?v=496616e2-15:1)
at jsxc.min.js?v=496616e2-15:1
at Object.success (ojsxc.js?v=496616e2-15:247)
at u (main.js?v=496616e2-15:25)
DevTools failed to parse SourceMap: https://my.domain/apps/ojsxc/js/jsxc/jsxc.min.js.map
DevTools failed to parse SourceMap: https://my.domain/core/js/dist/main.js.map
DevTools failed to parse SourceMap: https://my.domain/apps/ojsxc/js/jsxc/lib/jsxc.dep.min.js.map
DevTools failed to parse SourceMap: https://my.domain/core/js/dist/share_backend.js.map
DevTools failed to parse SourceMap: https://my.domain/core/js/dist/login.js.map

The problem only occurs when xcauth is running and XMPP server is set to "external".

I posted it here as well: https://github.com/jsxc/xmpp-cloud-auth/issues/84

**Comment by kerematam** [comment]
Apparently i am having exactly the same issue.

**Comment by kerematam** [comment]
I've solved. For my case; it was server having lack of disk space. So i have deleted some logs and add more disk space to server. Reboot.. Aaand voila!

**Comment by sualko** [comment]
Do you still get the error? Can you post your config? It would be interesting which circular structure it's trying to save.
