### ISSUE TITLE
E2E encryption questions

### ISSUE THREAD

**Issue by prog-amateur** [nextcloud/jsxc.nextcloud#130]
Hello, 

Sorry for opening an issue just because of a question. But, I think developers team are the best people to ask. 

Introduction in the [website](https://apps.nextcloud.com/apps/ojsxc) is not clear (we can understand two different meaning) : 

Are only chat conversations E2E encrypted or are videos and audio calls also encrypted? 

Thank you very much for your feedback.

**Comment by poVoq** [comment]
AFAIK WebRTC is used and thus yes video and audio calls should be encrypted.

Text messages will also be OMEMO encrypted in the new version.

What I am not sure about are uploaded files and pictures. It seems like not all OMEMO implementing clients also encrypt such files. Anyone knows how it is with JSXC?

**Comment by sualko** [comment]
> AFAIK WebRTC is used and thus yes video and audio calls should be encrypted.

That's right.

> Text messages will also be OMEMO encrypted in the new version.

If you enable OMEMO, yes.

> What I am not sure about are uploaded files and pictures. It seems like not all OMEMO implementing clients also encrypt such files. Anyone knows how it is with JSXC?

We are currently not encrypting file uploads, but there is a nice XEP from Danile, but it's hard to implement in browser. Therefore we will see encrypted file transfer not in the next release.
