### ISSUE TITLE
no updates?

### ISSUE THREAD

**Issue by susobaco** [nextcloud/jsxc.nextcloud#131]
Hello, version 17.0.1 no longer brings official support for this app. And I see that has since August without updating the code. someone knows if it is no longer maintained? are there other problems? Thanks

**Comment by sualko** [comment]
I'm currently busy in real life and had therefore no time to workaround a critical issue in jsxc for NC 17. Sorry, but I try to get a new version published as soon as possible. Maybe during the christmas holidays.

**Comment by susobaco** [comment]
Okay, thanks for your work.
