### ISSUE TITLE
Cannot see all NC users in roster with external mode

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/jsxc.nextcloud#136]
With internal mode of JSXC I see all users registered in the NC in my roster, while using external one I cannot do that. What should be changed to have this in place. Thank you.

**Comment by sualko** [comment]
You need to sync your roster with your nc db. Use a shared backend, like ldap and shared rosters. Or you can have a look at https://github.com/jsxc/xmpp-cloud-auth.

**Comment by ostasevych** [comment]
The matter is that I use xmpp-cloud-auth and users are logging with their accounts taken from LDAP. The question how to show them in the roster?

**Comment by sualko** [comment]
> users are logging with their accounts taken from LDAP

If you are using already an LDAP, please don't use xmpp-cloud-auth. Use ldap authentication for your xmpp server and use ldap shared rosters. Help for this is definitely out of scope for this application.
