### ISSUE TITLE
Opening xmpp links in NC

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/jsxc.nextcloud#143]
### Task:
Please, integrate opening the xmpp contacts in Nextcloud using jsxc. 

### What is now:
1. When clicking on the link of a contact from the Contacts search it suggest to use 3rd party application.

![image](https://user-images.githubusercontent.com/5199030/79612199-e7fa1500-8104-11ea-8d58-358c6ec8fb4c.png)

2. If I click on the icon in Contacts app close to the xmpp ID it open a new tab with the homepage of NC.
![image](https://user-images.githubusercontent.com/5199030/79612808-0ad8f900-8106-11ea-8b18-aa75e670e075.png)

### Expected behaviour: 
to start conversation with the selected interlocutor by opening proper window of the jsxc chat.

**Comment by sualko** [comment]
At least in 3.x this was working, so I have to look at it again.

**Comment by sualko** [comment]
Which version of JSXC are you using? How did you add the xmpp link to a contact?

**Comment by sualko** [comment]
> How did you add the xmpp link to a contact?

It's not intuitive that you have to click on "Skype" if you like to change the instant messenger.

**Comment by MarcelWaldvogel** [comment]
Great! It looks like this is specific to links within NC. Using [`navigator.registerProtocolHandler()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler) would allow any `xmpp` link (inside and outside of NC) to open OJSXC.

**Comment by sualko** [comment]
I didn't get it working and you have to provide a url for the handler which is also not optimal.

**Comment by ostasevych** [comment]
> Which version of JSXC are you using? How did you add the xmpp link to a contact?

4.0.0-beta. I think, it doesn't matter: either they are the users of NC, or contacts from the contacts app. If there's an xmpp field in NC it should be suggested to be processed by the appropriate handler of the jsxc app.
