### ISSUE TITLE
Redundant prompt about logging in with/without chat

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/jsxc.nextcloud#145]
With the version 4.0.0 whenever I am logging in I am prompted to login with chat or without chat.

![image](https://user-images.githubusercontent.com/5199030/79750623-ef463c00-8319-11ea-808f-56b2a02ede46.png)

Though in the settings it is checked the box "Enable chat on login".

![image](https://user-images.githubusercontent.com/5199030/79750400-9080c280-8319-11ea-8279-6734019901eb.png)

I assume, the system shouldn't ask me about this.

Additionally, which should be the behaviour of the the system, if I click the 3rd option just Login?..

**Comment by DanScharon** [comment]
> Additionally, which should be the behaviour of the the system, if I click the 3rd option just Login?..

that is defined by checking the box "Enable chat on login" or not. That's why offering three buttons is a feature: As a normal user I can't know what the default behaviour is ("Enable chat on log in" or not). That's why it's really helpful to always have both options as a dedicated button.

**Comment by ostasevych** [comment]
> > Additionally, which should be the behaviour of the the system, if I click the 3rd option just Login?..
> 
> that is defined by checking the box "Enable chat on login" or not. That's why offering three buttons is a feature: As a normal user I can't know what the default behaviour is ("Enable chat on log in" or not). That's why it's really helpful to always have both options as a dedicated button.

So, by now I have 3 options:
- just login
- login with chat
- login without chat

What should I check in settings in order not to ask users with or without, but start with the chat?

**Comment by DanScharon** [comment]
> What should I check in settings in order not to ask users with or without, but start with the chat enabled?

check the box "Enable chat on login". When they click on just login (or hit the enter button) they will start with chat enabled

**Comment by ostasevych** [comment]
> > What should I check in settings in order not to ask users with or without, but start with the chat enabled?
> 
> check the box "Enable chat on login". When they click on just login (or hit the enter button) they will start with chat enabled

That I understand. How to make not to show prompts before login?

**Comment by sualko** [comment]
> How to make not to show prompts before login?

You have to modify the source code and build your own version without those buttons.

**Comment by sualko** [comment]
It would be awesome if you could create a config option for that and open a pull request. :wink:

**Comment by ostasevych** [comment]
> It would be awesome if you could create a config option for that and open a pull request.

I am not so quick in coding... Is something behind the decision to have these prompts?.. in my opinion, they are only confusing users.

**Comment by sualko** [comment]
>  Is something behind the decision to have these prompts?

If we have user defined login behavior (which we want), than we can't know this configuration before the user hits enter. So if the global default is "no login" during start, but the user has defined "login on start", than he will only see a button "login with chat", because the global default is "no login". So the user has now no possibility to login without chat (what he probably wants some time).

**Comment by ostasevych** [comment]
> > Is something behind the decision to have these prompts?
> 
> If we have user defined login behavior (which we want), than we can't know this configuration before the user hits enter. So if the global default is "no login" during start, but the user has defined "login on start", than he will only see a button "login with chat", because the global default is "no login". So the user has now no possibility to login without chat (what he probably wants some time).

Principally, you may obtain the settings once a user inserted his/her name in the login field by reading proper information from his/her account.

Also, I think, if a user decided to join without chat he/she may easily switch it off after logging in by going to the proper section and disabling its start after login. Then logout and login again.

Believe me, having 3 options of logging in is super confusing...

**Comment by sualko** [comment]
> Principally, you may obtain the settings once a user inserted his/her name in the login field by reading proper information from his/her account.

If you think that works good, I appreciate any pull request. But you have to make sure that this doesn't expose if a username exists. In my point of view this is no important information, but this is the way NC handles user authentication. So I don't want to break with that.

**Comment by elvisef** [comment]
Alright, so the author wrote the addon, and he cannot make any changes to the source code ? Weird... The option to change behaviour of ADDITIONAL login buttons should be the first thing to do in settings, to have user possibility to change visibility of the buttons.

Anyway, "Enable chat on login" - this line as understand as: "please enable chat, just after I logged in", but NOT "show buttons on login screen".

So I would change this mistakenly named line to another suggestion.
