### ISSUE TITLE
OMEMO Fingerprinting

### ISSUE THREAD

**Issue by shimmy11** [nextcloud/jsxc.nextcloud#146]
Hi everybody, thanks for all the work.

I wanted to report a problem communicating OMEMO between JSXC 4.0.0 and Conversations 2.7.1
Between Conversations instances it works reliable, so that is not the issue.

In Conversations:
Trust Fingerprints
Unable to fetch device bundles

In JSXC:
OMEMO devices of your contact

No devices available

Error: Your contact does not support OMEMO.

**Comment by sualko** [comment]
I also get sometimes the same error message, but it works nonetheless most of the time. If not, try to restart conversations. It's not optimal, but without an Conversation error log I have no idea what is going on.
