### ISSUE TITLE
Cannot remove "login with ..." and "login without ... " chat buttons

### ISSUE THREAD

**Issue by elvisef** [nextcloud/jsxc.nextcloud#147]
How can I do this ? I have no settings to use to remove these buttons.
Buttons are not needed and I want to remove it.
![29042020_09:44:29_Zaznaczenie](https://user-images.githubusercontent.com/25976749/80572660-f3034e00-89fe-11ea-8634-be924ce8e026.png)

**Comment by sualko** [comment]
There is no build in option for that. Please create a pull request if you like to have this possibility.

**Comment by ostasevych** [comment]
See #145
