### ISSUE TITLE
OMEMO lock cannot turn green

### ISSUE THREAD

**Issue by Luticus** [nextcloud/jsxc.nextcloud#148]
Minor issue really, but it would look better if resolved.  

Basically the OMEMO lock can only ever be orange at best because your key listed for "this device" cannot be verified and only comes stock as recognized (orange).  You should set this key as verified by default as it is effectively the device you're chatting from and should be automatically verified.  If you can't trust yourself, then who can you trust?  :)

**Comment by sualko** [comment]
You are absolutely right. I will try to fix it in the rc. Thanks for mentioning.

**Comment by Luticus** [comment]
@sualko Well the new version has the key marked confirmed, but for some reason the lock icon in chat is still orange.  :)  not sure what that's about, but I figured I'd point it out.

**Comment by sualko** [comment]
> the lock icon in chat is still orange

I think I missed to check if all devices are confirmed. Will be fixed in the next version. Thanks for pointing this out.
