### ISSUE TITLE
every new versoin is worse.

### ISSUE THREAD

**Issue by bgman111111** [nextcloud/jsxc.nextcloud#149]
Hi.

I had working jxcs version and it worked with ejabberd. Other day it just upgrade and now it comment " oauth " hey return cram-md5 or what default scraft with sql it connect. It was worked, FUCK YOURELF. im not developer and it work i had to seek in internet with HOURS. /to make it work. This oauth has to be choose if SOMEONE want to use it or not. no jxcs decide what is best for user. User is who decide if he want to use oauth or not. Include with xcauth when acive it comment downgrade TLS, no way wy don't you uninstall android apps and all your conversations ARE GONNA BE DELETED. downgrade it mean it will downgrade TLS SECURITY. it was wroking. Is tere someone who check if this developers are do good or bad in nectcloud or they pyut malware. Someone can uited hackers and investigate if nextcloud it real transparency or spyware. becouse looking ow bad jxcs is made it conclusion developers are conspiring. Include jcxs has obsolete manual i find bad command that it dont exist. I will live to users find them. blackperyy pi pfuuu,,, why there is no complete manual what it is. Did somoene see nextcloud 18 admin manuals... They are very SIMPLE EXPLAINED. BRAVOOOOOOO for who make it. Nextcloud if you read bant this jcxs developres they are BREAKING nextcoloud. Now im gonna complaint against nextcloud mail. Becouse there they had make shits there too....

**Comment by sualko** [comment]
https://github.com/jsxc/jsxc/blob/master/CODE_OF_CONDUCT.md
