### ISSUE TITLE
scrolling

### ISSUE THREAD

**Issue by Luticus** [nextcloud/jsxc.nextcloud#150]
Wasn't sure If anyone else had noticed this but it seems i've lost the ability to scroll back through a conversation.  So when I have a chat open or I open a new one and load older messages I can't scroll up.

I tested this on the newest firefox.

**Comment by sualko** [comment]
Do you mean, after to loaded some messages from mam (archive)?

**Comment by Luticus** [comment]
I mean no messages will scroll, that was just one example.  If someone is chatting with me, once their chat goes beyond the size of the window, I can't scroll back up.  I even started firefox with a brand new default profile to see if any plugins or browser settings might still be affecting it, but it still does it, even on a different machine.

**Comment by Luticus** [comment]
It looks like scrolling does work in chromium though, so whatever is going on it's a firefox thing.

**Comment by sualko** [comment]
I think this is a duplicate of jsxc/jsxc#873 and therefore I close this issue. If you have any idea how I can reproduce this, any help would be appreciated.
