### ISSUE TITLE
Problem with TLS certificate

### ISSUE THREAD

**Issue by susobaco** [nextcloud/jsxc.nextcloud#151]
Hello, I'm trying to log in with the dino client, from my palautgn.jsxc.ch node and I get an error in the TLS negotiation (the certificate has expired). The node's domain certificate has just been renewed. Is it a problem with my node or jsxc.ch?

**Comment by sualko** [comment]
@MarcelWaldvogel I think the dns resolution of our managed server is not working anymore. Can you check that?

**Comment by susobaco** [comment]
To: jsxc.ch
IPv4 & IPv6 = 85.195.224.26 (85-195-224-26.fiber7.init7.net)
MX: smtp.netfuture.ch (10)
NS records: ns1.netfuture.ch (87.245.127.186)
                    merkur.corvent.ch (185.66.108.108)
                    win.jsxc.ch (85.195.224.26)
SOA records: Primary nameserver : win.jsxc.ch
                      Hostmaster E-mail address : marcel.jsxc.ch
                      Serial : 2019150717
                      Refresh : 3600
                      Retry : 1800
                      Expire : 2419200
                      Default TTL : 60 
TXT records: v=spf1 include:domainssaubillig.de ~all 
SRV records : Not found
CNAME records: xmpp.jsxc.ch (TTL : 28799) 
 whois jsxc.ch
Requests of this client are not permitted. Please use https://www.nic.ch/whois/ for queries.

**Comment by susobaco** [comment]
https://xmpp.net/result.php?domain=palautgn.jsxc.ch&type=client

**Comment by MarcelWaldvogel** [comment]
Sorry for the delay. The certificate for the domain (and one other) failed to renew; it worked for all others. The problem has been fixed now.

(Somehow, [`acme.sh`](https://acme.sh) which we use for certificate generation forgot to record one parameter for two of the domains recently created, one of them being yours, so the automatic certificate renewal process did not know what to do. Workaround has been established and the two config files fixed manually, so it should not occur again. Sorry!)

**Comment by MarcelWaldvogel** [comment]
See https://xmpp.net/result.php?domain=palautgn.jsxc.ch&type=server (the client can only be retested later).

![image](https://user-images.githubusercontent.com/3014737/83859602-71e65780-a71e-11ea-90e9-637447d80ac5.png)

**Comment by susobaco** [comment]
Fantastic, thank you very much, and no problem for the delay.
Salud!
