### ISSUE TITLE
Unavailable status by default

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/jsxc.nextcloud#152]
Wherever I am logging in to the NC, I have to change the status from Out of the network to Online manually. Should be Online after login if enabled in settings.
![image](https://user-images.githubusercontent.com/5199030/84442929-4811c100-ac47-11ea-83b8-150e5be30a0b.png)

**Comment by sualko** [comment]
Can you send me some test credentials to klaus@jsxc.org? I think that would be the easiest thing.

**Comment by ostasevych** [comment]
It seems, with 4.1.1 the issue has gone. Thank you!
