### ISSUE TITLE
Roster overlaps UI elements in NC

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/jsxc.nextcloud#153]
In some apps the roster overlaps the UI elements of some Nextcloud apps, which complicates the access, to them, in particular:

1. Talk app
2. Forms app
3. Maps app
4. Tasks app
5. Users (User management)
6. Notes app
7. Files app (partially, when clicking over Details)

OJSCX 4.1.1, Nextcloud 19.0.0.12

**Comment by sualko** [comment]
I close this issue, because one is enough.
