### ISSUE TITLE
Attaching files from Files app

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/jsxc.nextcloud#154]
Quite often it is necessity to share the files, which are already in Nextcloud using Files App.
Please, add this function.

![image](https://user-images.githubusercontent.com/5199030/85331761-65644c00-b4df-11ea-8f1f-6395eb09e107.png)

So, a user may click over attach button and be prompted to upload either from Files or from Desktop.

**Comment by sualko** [comment]
That would be a nice feature, pr welcome. See #83.
