### ISSUE TITLE
A/V calls interoperability with Conversations

### ISSUE THREAD

**Issue by piti-diablotin** [nextcloud/jsxc.nextcloud#156]
Hi,
This might be a stupid question so ....
I recently manage to make A/V calls work between 2 ojsxc sessions and between 2 Conversations(android) app.
Now I would like to make it work between one ojsxc session and one Conversations. Is that possible ? 
When I read the doc from Converstations, the XEP required do not all seem to be implemented in JSXC ?
https://gist.github.com/iNPUTmice/a28c438d9bbf3f4a3d4c663ffaa224d9#notes-for-developers and https://www.jsxc.org/features.html
However both say that they support E2E encryption. For sure Conversations supports DTLS+SRTP. What about JSXC ?
Would it be hard to make both compatible ?
Thansk in advance.

**Comment by sualko** [comment]
You are right, we miss one XEP and therefore calls are only possible if every participant uses one client. See https://github.com/jsxc/jsxc/issues/890#issuecomment-647150657 for more details. If you like to work or sponsor this feature, please get in touch with me.

**Comment by piti-diablotin** [comment]
I can give a try if there is no hurry :smiley:

**Comment by sualko** [comment]
Every contribution is appreciated. :+1:

**Comment by piti-diablotin** [comment]
Is there a manual or something to go into jsxc code (for developers?) and learn how things work?
