### ISSUE TITLE
Nextcloud 19 css making msg send input black

### ISSUE THREAD

**Issue by deusoz** [nextcloud/jsxc.nextcloud#157]
when using high contrast WITH the dark theme that is.. and I didn't like it. so if anyone else has same gripe, here is css to make the send input keep a light background during hover, etc:

.jsxc-send-area textarea, textarea.jsxc-message-input, textarea.jsxc-message-input:active, textarea.jsxc-message-input:focus, textarea.jsxc-message-input:not(:disabled):active, textarea.jsxc-message-input:not(:disabled):hover, textarea.jsxc-message-input:not(:disabled):focus {
background-color: rgba(22,22,22,.1) !important;
color: #222 !important;
padding-left: .4rem;
padding-bottom: .7rem;
}

**Comment by deusoz** [comment]
if you lost regular messages like that as I realized happened the next day... add this:  .jsxc-content>p {color: #777; }

**Comment by deusoz** [comment]
Hmm, today I realize that other dialogs also unreadable in high contrast + dark mode... one more css lines fixed that:
.jsxc-dialog {background: black !important; }
Also note by language setting was crowding setting pulldown.. so
.jsxc-list__text__secondary { margin-right: .7rem; }

**Comment by sualko** [comment]
Thanks for your report. This is a known issue jsxc/jsxc#834, but until now we had no resources to fix it. I will try to enhance the support for dark theme, but I could need some help. So if you have time, a pr would be appreciated.

**Comment by sualko** [comment]
I started to work on this (see the post in the linked issue) and I will keep track of the issue in jsxc/jsxc#834.
