### ISSUE TITLE
it is possible for the chat app to be active when nextcloud is in a logged out state.

### ISSUE THREAD

**Issue by Luticus** [nextcloud/jsxc.nextcloud#159]
One of my users reported this odd situation today and I thought I should pass it on because it looks odd and the app should probably not behave this way. Basically the login screen for nextcloud should probably destroy open jsxc sessions and hide the chat sidebar and open windows. These windows and sidebar apps should also probably remain hidden though the log in process if 2FA apps are enabled and in use.

Here's his comments about how he got it into this state:  "I went back to my logged in tab of Nextcloud from the other day. Chat inside Nextcloud was offline, so I selected my status and set it to online, which brought up a sign in modal. I signed in, then Nextcloud decided I wasn't logged in enough, so it took me back to the login screen for the site... but chat persisted"

Nextcloud decided he wasn't logged in enough because his cookie timed out but his page was still cached so it "looked" like he was logged in, even though he wasn't, which is why it took him back to the sign in page.

here's a redacted screen shot of the situation in action:
![Screen_Shot_2020-11-17_at_12 06 15_PM](https://user-images.githubusercontent.com/7807109/99425017-58058f00-28d0-11eb-87f7-b2b62aacf14f.jpg)

**Comment by sualko** [comment]
Thanks for your report. You are right. This is annoying and should not be happen. Will be fixed in the next release.

**Comment by Luticus** [comment]
Thanks!
