### ISSUE TITLE
call rining doesn't stop when answered

### ISSUE THREAD

**Issue by Luticus** [nextcloud/jsxc.nextcloud#162]
Sometimes the call ring doesn't stop when answered and the only way to stop it is to refresh the page. I notice it more when I have other devices involved such as a browser call from one computer to another while also being logged into conversations app on my android phone. It also happens if I answer with another device where the call will ring on the browser until it is refreshed. Using newest version of JSXC and ejabberd 20.07 as my chat server with turnserver configured. It looks like firefox will even do this on browser to browser calls. 

This may be a firefox issue, some testing shows it works better on chromium.

**Comment by sualko** [comment]
I'm sorry you have issues, but I guess this is related to jsxc/jsxc#1014 and could also be fixed via jsxc/jsxc#890. Therefore I close this issue here. Please follow the other ones.

**Comment by Luticus** [comment]
Thanks, I am definitely having connection issues between conversations and jsxc so that's part of it, not sure if the ringing issue is related or it's own thing but I'll follow the other issues as you suggest and let you know if they resolve everything.  Thanks for your help!
