### ISSUE TITLE
Update app for Nextcloud 20?

### ISSUE THREAD

**Issue by thkoch2001** [nextcloud/jsxc.nextcloud#163]
I was suprised not to find this app in my new Nextcloud 20 instance until I realized that this is probably due to the version restriction:

https://github.com/nextcloud/jsxc.nextcloud/blob/master/appinfo/info.xml#L49

Is there any change needed beside dumping the version range limit up to 21? Are there blockers? Do you have a timeline?

I'd love to try this app out.

Do you have any pointers to the long term strategy of Nextcloud with Talk vs. XMPP? I'm worried that Nextcloud might go the way of all comercial entities and try to abandon freedom (XMPP) for profit (proprietary Talk with Nextcloud's High Performance Backend).

**Comment by sualko** [comment]
This application works flawless with Nextcloud 20. The max attribute describes the maximum version (including). Maybe you have to search for xmpp or ojsxc.

 > Is there any change needed beside dumping the version range limit up to 21? Are there blockers? Do you have a timeline?

Usually we try to release a compatible version with the first RC release, but this also depends on the jsxc core development. Currently there is still a lot to do and I'm not sure if we can release a new version with NC 21.

> I'd love to try this app out.

And we would love to hear your feedback :+1:

> Do you have any pointers to the long term strategy of Nextcloud with Talk vs. XMPP?

We had discussions with Nextcloud before Talk was developed and the overhead and requirements did not fit with a xmpp solution. Therefore Talk is independent, but it provides bridges to most networks.

> try to abandon freedom (XMPP) for profit (proprietary Talk with Nextcloud's High Performance Backend)

You can always use our app :wink:, but I don't see any issues with this in the near future. For example they release the hpb some time ago and they really try to support open and federated solutions, which I know from many personal meetings.

**Comment by thkoch2001** [comment]
Sorry for my wrong fear. However I search for XMPP or ojsxc and there are no results.
I compared the downloaded apps.json from https://apps.nextcloud.com/api/v1/apps.json with the one in the appstore directory on my NC instance. The downloaded apps.json contains your app but the one in my appstore directory doesn't.

So I guess that the app gets filtered out here:
https://github.com/nextcloud/server/blob/3a9c7f99f632f973caaf6a7aca5ca9294bb11db3/lib/private/App/AppStore/Fetcher/AppFetcher.php#L97

But I can't figure out why it gets filtered out:

- There is no exception from appstoreFetcher in the logs
- The PHP version is 7.3.19
- The NC version is 20.0.6

I should open an issue against Nextcloud to improve this code. There should rather be a filter in the apps store to allow me to also search in apps that do not match and then to exactly show me why they don't match.

**Comment by sualko** [comment]
> I should open an issue against Nextcloud to improve this code

Sounds like a good idea. Would be nice if you could cc me or link this issue, because it's also interesting for me. You can also try to download this app directly from Github and check if it's reporting any issues while enabling.

**Comment by thkoch2001** [comment]
I upgraded Nextcloud to 20.0.7 and now it shows the "JavaScript XMPP Chat" app.

I hope I'll have time later this year to become a NC dev and contribute to stability of the platform...
