### ISSUE TITLE
Unable to connect to jsxc.ch server

### ISSUE THREAD

**Issue by susobaco** [nextcloud/jsxc.nextcloud#166]
For some time now, and for no apparent reason, the chat does not connect to the jsxc.ch server. If I try to register my server again I get this error:

_Error: file_get_contents(https://xmpp.jsxc.ch/registration?rid=k3y5ft8xUeobJSGgFerl):  failed to open stream: Connection refused at  /var/www/html/nextcloud/apps/ojsxc/lib/DataRetriever.php#19<<closure>>OC\Log\ErrorHandler::onError(2, "file_get_co ... d", "/var/www/ht ... p", 19, { url: "http ... l})/var/www/html/nextcloud/apps/ojsxc/lib/DataRetriever.php - line 19: file_get_contents("https://xmp ... l", false, null)/var/www/html/nextcloud/apps/ojsxc/lib/Controller/ManagedServerController.php - line 100: OCA\OJSXC\DataRetriever->fetchUrl("https://xmp ... l", { 0: "And 1  ... "})/var/www/html/nextcloud/apps/ojsxc/lib/Controller/ManagedServerController.php - line 63: OCA\OJSXC\Controller\ManagedServerController->doRegistration(null, "k3y5ft8xUeobJSGgFerl")/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: OCA\OJSXC\Controller\ManagedServerController->register(null)/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: OC\AppFramework\Http\Dispatcher->executeController(OCA\OJSXC\Co ... }}, "register")/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch(OCA\OJSXC\Co ... }}, "register")/var/www/html/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main("ManagedServerController", "register", OC\AppFramew ... {}, { _route: "o ... "})/var/www/html/nextcloud/lib/base.php - line 993: OC\Route\Router->match("/apps/ojsxc ... r")/var/www/html/nextcloud/index.php - line 37: OC::handleRequest() |  
-- | --_

I have also noticed that from Dino I can access the accounts, but it is impossible to send files.
Do you need any more information?
Thank you.

**Comment by sualko** [comment]
@MarcelWaldvogel  can you check that?

**Comment by susobaco** [comment]
Hi, I have installed a prosody server on debian buster, and I finally got it to connect. I am using nginx for the nextcloud server and I had to add the following to the /etc/nginx/conf.d/nextcloud.conf file:

_location /http-bind {
        proxy_pass  https://localhost:5281/http-bind;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        tcp_nodelay on;_

As long as I did not change this line, it was impossible to connect:
_proxy_pass  https://localhost:5281/http-bind;_

**Comment by poVoq** [comment]
The entire: https://jsxc.ch/managed seems to be down.

Maybe remove the option if that service isn't offered anymore?

Was there any software involved that could be open-sourced to allow someone else to offer a similar service?

**Comment by sualko** [comment]
Sorry for the inconvenience. @MarcelWaldvogel can you check that? Is that the aftermath of the datacenter failure? The http upload server also seams to be down.
