### ISSUE TITLE
4.3.0 Layout broken in Nextcloud 20.0.10

### ISSUE THREAD

**Issue by johndoe7000** [nextcloud/jsxc.nextcloud#173]
![grafik](https://user-images.githubusercontent.com/35802969/124639827-e6914580-de8c-11eb-894e-157731bd93f1.png)

Also names are now hardly readable.

**Comment by sualko** [comment]
Did you refresh your cache? Can you try it in a private window?

**Comment by johndoe7000** [comment]
Tried that right now but no change.

**Comment by sualko** [comment]
Sorry, but it seams this is not my best release. We will release a bug fix tomorrow. Sorry for the inconvenience.
