### ISSUE TITLE
Chat user list has graphical issues

### ISSUE THREAD

**Issue by Luticus** [nextcloud/jsxc.nextcloud#177]
![image](https://user-images.githubusercontent.com/7807109/141669172-b03fc552-00d1-41b9-9740-232c4f918395.png)

As you can see by the image the chat box is showing up a bit broken regarding the contacts section. This only seems to impact the contacts section and doesn't seem to affect any other aspect, including the groups area.

As indicated, this happens in both the newest Firefox and also the newest Google Chrome browsers.

Ignore the blurring as the image is censored for the privacy of the users involved in the screen shot.

**Comment by sualko** [comment]
Thanks for letting us know that. I will look into it.
