### ISSUE TITLE
Problem with chat app 

### ISSUE THREAD

**Issue by eneoshoshari** [nextcloud/jsxc.nextcloud#22]
The issue is that when logged in as “admin” the chat works fine, but when logged in as a simple user the chat requires re-authentication and the credential are not valid. 
 
Eneo

**Comment by sualko** [comment]
We need more information:

- Which version do you use?
- Which backend do you use?
- Any errors in your js console?
- Any errors in your nc log?

**Comment by eneoshoshari** [comment]
OS ubuntu 16.04
nextcloud 12.0
Openfire 4.1.4
Javascript XMPP Chat 3.2

**Comment by eneoshoshari** [comment]
i have change OS version , i used centos 7 , nextcloud 11 ,and do it the same thing .
"Authentication failed with the chat server. Maybe the password is wrong?
Cancel "

**Comment by sualko** [comment]
- Any errors in your js console?
- Any errors in your nc log?

**Comment by eneoshoshari** [comment]
no no , when I login like admin ,it work perfect , but when I login another user .

**Comment by sualko** [comment]
I understood your issue, but please answer my questions.

**Comment by eneoshoshari** [comment]
I don't have any errors ,if you understand me .

**Comment by sualko** [comment]
Please enable [debug mode](https://github.com/jsxc/jsxc/wiki/Debugging), watch any outgoing connection and check your openfire log for errors. In the past such errors occurred because the normal user had special characters in their username.
