### ISSUE TITLE
NC12: No admin icon

### ISSUE THREAD

**Issue by MarcelWaldvogel** [nextcloud/jsxc.nextcloud#26]
All the other admin panels in Nextcloud 12 have an icon, except JSXC. Please add our nice icon there as well.
![Admin panel selection menu](https://user-images.githubusercontent.com/3014737/27048612-cef4b6be-4fac-11e7-8844-11120bdbfd53.png)

**Comment by sualko** [comment]
This is currently not possible, because we need to stay backwards compatible.
