### ISSUE TITLE
XMPP 3.2.1 nextcloud12 and External sites issue

### ISSUE THREAD

**Issue by tedd77** [nextcloud/jsxc.nextcloud#27]
I am encountering a problem with XMPP when using External sites in nextcloud 12.

The scenario 
While working with a site (link to an External site) that was opened within nextcloud 12 
should the XMPP is suddenly used then there is no way that the keyboard will work inside the external site window however the mouse will work.
Should I do F5 then the keyboard will resume but that will result in losing the data entered on the screen.

**Comment by sualko** [comment]
How can you open an external site inside nextcloud?

**Comment by tedd77** [comment]
I use the nextcloud External sites application , this will allow you to open a new frame within nextcloud window.

**Comment by sualko** [comment]
Ok, but how does jsxc influence this external site? It's not clear to me.

**Comment by tedd77** [comment]
I do not know. The moment someone sends a message while the external site is on then keyboard stops.
Should no message or no focus on xmpp while working on external site we do not encounter any issue.
Maybe the Java or some script. We do not know. 

Regards

**Comment by sualko** [comment]
I can't reproduce your issue. I included https://www.startpage.com into my nextcloud installation, but even if messages are incoming, I can use my keyboard as usual.

Try to check your javascript console.

**Comment by tedd77** [comment]
I was able to solve the problem.
In fact that was a vnc server external link. In order to solve the problem we made a shortcut to the visual keyboard. Upon the problem , since the mouse has no issues, pressing the escape on the visual keyboard solves the problem as of when it is encountered.
Thank you for your continuous and high standard support.
