### ISSUE TITLE
Don't show deactivated users or users not in same group(s)

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/jsxc.nextcloud#29]
I just happened to have some deactivated users with NC 12.0.0. They all show as possible offline chat partners.

The thing is, they are deactivated because they are currently not working for the company but might do so again. The same is true for some 'external' users which seldom log on and are not supposed to see the whole company and therefore are in their own group 'external'.

I am not sure if this is a bug, or feature request. But it would be nice to only sow the users that are actually in the same group -- since I assume that 'deactivated' users are basically just another group.

I am using the experimental internal feature of this wonderful app.

**Comment by MarcelWaldvogel** [comment]
The internal XMPP server is great for starting, but not (yet😉) ready for enterprise requirements. You might want to try using an external XMPP server. Some installation instructions are in https://github.com/jsxc/xmpp-cloud-auth . (If you have a choice, go for ejabberd, as the Prosody authentication module which connects to the JSXC authentication bridge back to Nextcloud is alpha-quality. Of course, authentication directly against LDAP ist also an option, just not explained there.)
