### ISSUE TITLE
Password synchro

### ISSUE THREAD

**Issue by jybeeL** [nextcloud/jsxc.nextcloud#3]
hi, 

i don't know if i'm in the good endroit to send my question. In the doubt, i ask here.

I use Nextcloud with the JavaScript XMPP's app.
In another serveur i have installed Openfire.
The relation betwin the 2 servers works.

Actualy, I must to create users in openfire and after i can log in with one new user in XMPP's app in nextcloud.

I don't use Ldap authentication, all my users's password are in Databases (openfire & nextcloud)

I want users could specifiy theirs password for openfire.
(i dont want to know the users passwords)
But i dont know how i can offer for all user the possibility to choose theirs password for openfire.

Users specify already their nextcloud passwords.
Is it possible to synchronise passwords user betwin the two databases ?

Thx

**Comment by sualko** [comment]
Please read the last post in #2.
