### ISSUE TITLE
Drop support for NC9

### ISSUE THREAD

**Issue by sualko** [nextcloud/jsxc.nextcloud#40]
According to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule Nextcloud 9 has reached his end of life. @LEDfan can we increase the min version?

**Comment by LEDfan** [comment]
This is okay for me. Less older versions will make development easier :) And the camel-casing of #39 will work too :)

**Comment by sualko** [comment]
Is it ok for you, if I do it #39, or is this something which should go in a separate pr?

**Comment by LEDfan** [comment]
Yes, it will make things easier!

**Comment by sualko** [comment]
What makes things easier? :wink:

**Comment by LEDfan** [comment]
Oops, I meant that doing it in #39 will make it easier :see_no_evil:
