### ISSUE TITLE
Add php-cs-fixer to have same code style as NC server

### ISSUE THREAD

**Issue by sualko** [nextcloud/jsxc.nextcloud#43]
See nextcloud/server#5859 

@LEDfan pro/con?

**Comment by LEDfan** [comment]
I really like this! I guess we have to run it once on the full code base and then make sure every commit is complaint. 

If we add it to travis I would make sure it's (one of) the last step, so we don't have to wait until it has run before we know if the tests passes.

**Comment by sualko** [comment]
Great. Would you like to start working on #42 or #43?
