### ISSUE TITLE
Enabling jsxc breaks creating account in android app

### ISSUE THREAD

**Issue by p5n** [nextcloud/jsxc.nextcloud#47]
As I understand latest android app logins using web form. I cannot add new account with jsxc enabled probably because of it modifies login page.

After disabling I was able to do it. Not sure, may be it is android app bug.

android app is dev version from f-droid (20170724)
jsxc 3.2.1

**Comment by sualko** [comment]
Thanks for reporting. We keep track of this in jsxc/jsxc#584.
