### ISSUE TITLE
Do we need to ship the vendor folder?

### ISSUE THREAD

**Issue by sualko** [nextcloud/jsxc.nextcloud#48]
Currently we include the hole vendor folder with every release. @LEDfan is this necessary?

**Comment by sualko** [comment]
I did some quick tests and it seems that we don't need the vendor folder, so I will exclude it.

**Comment by LEDfan** [comment]
Just to confirm, it shouldn't be needed anymore, the only run-time dependency is sabre/xml but this has been available for sure since stable10 (probably earlier).
