### ISSUE TITLE
JSXC icon only appears in admin settings, not in user settings

### ISSUE THREAD

**Issue by MarcelWaldvogel** [nextcloud/jsxc.nextcloud#50]
A fix similar to 36a9d7a12906021972dac86de089bcd3a1a86911 should be applied to the user settings as well

**Comment by sualko** [comment]
Sections are currently only supported in the admin settings by Nextcloud.

**Comment by MarcelWaldvogel** [comment]
How come all the other parts (if they are not sections) have icons in NC12?
![noicon](https://user-images.githubusercontent.com/3014737/28743201-35982df4-7444-11e7-8363-77ba5f0a933e.png)

**Comment by sualko** [comment]
I don't know, but as the documentation says " Registering personal settings 
follows and old style yet. ". 
https://docs.nextcloud.com/server/12.0/developer_manual/app/settings.html

**Comment by MarcelWaldvogel** [comment]
Including the typo, this has not changed since 10.0:  https://docs.nextcloud.com/server/10.0/developer_manual/app/settings.html

Also, e.g. federatedfilesharing already uses the new API: https://github.com/nextcloud/server/blame/master/apps/federatedfilesharing/lib/Settings/PersonalSection.php

So, I guess the documentation is just outdated. Let me open a ticket in nextcloud/server

**Comment by sualko** [comment]
I will have a look at it. The issue should be opened at the documentation repo.

**Comment by MarcelWaldvogel** [comment]
Which it was :-)

**Comment by sualko** [comment]
Ok, personal sections will be added in NC 13 and before the use css classes to inject icons. E.g. the jsxc entry has the class `nav-icon-javascript-xmpp-client`.

**Comment by sualko** [comment]
![screenshot from 2017-07-31 15-48-51](https://user-images.githubusercontent.com/2974196/28780643-c9a4ce34-7607-11e7-941f-41c5591b5c7c.png)
