### ISSUE TITLE
Can't register managed server

### ISSUE THREAD

**Issue by sualko** [nextcloud/jsxc.nextcloud#55]
### Environment
- **PHP version:** 5.6
- **NC version:** 11
- **JSXC version:** 3.3.0-beta.1

### NC Logs

```
OCP\AppFramework\QueryException: Could not resolve dataRetriever! Class dataRetriever does not exist
.../nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('dataRetriever')
.../nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 544: OC\AppFramework\Utility\SimpleContainer->query('dataRetriever')
.../nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 73: OC\AppFramework\DependencyInjection\DIContainer->query('dataRetriever')
.../nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 96: OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
.../nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\OJSXC\\Contr...')
.../nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 544: OC\AppFramework\Utility\SimpleContainer->query('OCA\\OJSXC\\Contr...')
.../nextcloud/lib/private/AppFramework/App.php - line 101: OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\OJSXC\\Contr...')
.../nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\OJSXC\\Contr...', 'register', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
.../nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
.../nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/ojsxc/man...')
.../nextcloud/index.php - line 40: OC handleRequest()
{main}
```

**Comment by sualko** [comment]
The error message is completely misleading. It failed, because `$c->query('URLGenerator')` failed. I had to replace all query statements with something like this:

```
\OC::$server->getURLGenerator(),
\OC::$server->getConfig(),
\OC::$server->getUserSession(),
$c->getServer()->getLogger(),
$c->getServer()->getSecureRandom(),
```

According to the [app manual](https://docs.nextcloud.com/server/12/developer_manual/app/container.html), we have to use a namespaced variant:

```
$c->query('OCP\IURLGenerator'),
$c->query('OCP\IConfig'),
$c->query('OCP\IUserSession'),
$c->query('OCP\ILogger'),
$c->query('OCP\Security\ISecureRandom')
```

@LEDfan do you know why it works on NC 12? Did you know that there is [automatic dependency assembly](https://docs.nextcloud.com/server/12/developer_manual/app/container.html#use-automatic-dependency-assembly-recommended)? We just have to update `routes.php` (in an further release).

**Comment by LEDfan** [comment]
> The error message is completely misleading

It really is! There is a WIP patch https://github.com/nextcloud/server/pull/5938 to give better errors.

> do you know why it works on NC 12? 

Absolutely not, I don't know of any changes in the DI stuff since 12.

> Did you know that there is automatic dependency assembly?

I heard about it and I guess it's a good idea to move most of the services to it (some will have to stay hard coded because they need some special logic). Maybe refactor it after the 3.3 release, together with moving the files to CamelCase?

**Comment by sualko** [comment]
> Maybe refactor it after the 3.3 release, together with moving the files to CamelCase?

Sounds great. I would like to release a second beta this weekend, so we can release the final version before the nc conf.
