### ISSUE TITLE
Chat does not work when username contains '@' 

### ISSUE THREAD

**Issue by alxarce** [nextcloud/jsxc.nextcloud#59]
Steps to reproduce

Create users:
Create two users accounts with username contains '@' like abc@test.com and cde@test.com

Enable JavaScript XMPP Chat (v 3.2.1)

Configure JavaScript Xmpp Client as Internal

Login with: abc@test.com and cde@test.com, start a chat and send a messages between this accounts

Expected behaviour

Messages sent from abc@test.com to cde@test.com are sent successfully

Actual behaviour

Messages sent from abc@test.com to cde@test.com do not arrive

Server configuration

Operating system: Ubuntu 16.04
Nextcloud version: 12.0.2
Database: Postgresql 9.6
Web server: Nginx
PHP version: 7.0

**Comment by sualko** [comment]
cc @LEDfan

**Comment by LEDfan** [comment]
@alxarce thanks for reporting this bug! I fixed it in #64, if you have a moment please test the attached test archive.

**Comment by alxarce** [comment]
it's working fine with attached archive in #64.
