### ISSUE TITLE
When activating jsxc addon, user can not login to nextcloud anymore

### ISSUE THREAD

**Issue by yennor** [nextcloud/jsxc.nextcloud#69]
I've got a working prosody server running. Normal clients can connect without any problems to it. So I also wanted to get the nextcloud client working with it.
I've setup bosh.
If I enter in my browser:
https://mydomain.com/http-bind/
I get
`It works! Now point your BOSH client to this URL to connect to Prosody.`
So it seems like bosh is setup correctly.
Also the config dialog of  nextcloud xmpp client tells me, after entering the bosh url:
`BOSH Server reachable.`
So I've logged out, and then tried to log in again.
What wouldn't work. I just get an endless spinning wheel.

The browser debugging console tells me:
```Content Security Policy: Ignoring duplicate source 'unsafe-inline'  (unknown)
Content Security Policy: Couldn’t parse invalid host 'unsafe-inline'  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-Z0J0MXFYSzdLUE9IcHNLdU9wRUxNSWpMV1FHZXJjc04vNHdCQ2FaK0NzTT06MEg4aC9RTDJhOHIva0xYOUF0eDVYTTJNTERPcC9PQjhsY0oxV3RRd1hMcz0=' 'unsafe-eval'”). Source: (function s(t,n,e,r){t.initialize(n,e,r)....  login:1
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
State changed to INITIATING  jsxc.min.js:13:1885
Try to relogin  jsxc.min.js:13:1885
Logout was forced or I found no valid jid  jsxc.min.js:13:1885
State changed to TRYTOINTERCEPT  jsxc.min.js:13:1885
State changed to INTERCEPTED  jsxc.min.js:13:1885
Use of Mutation Events is deprecated. Use MutationObserver instead.  bug-78414_content.js:70:2
State changed to ESTABLISHING  jsxc.min.js:13:1885
New connection  jsxc.min.js:13:1885
CONNECTING: null  jsxc.min.js:13:1885
```

Prosody.log 
` mod_bosh	info	New BOSH session, assigned it sid 'be9fb13c-643d-4d5f-9fa7-9302f2f89993'`

apache errorlog doesn't show anything

nextcloud.log also doesn't show anything. only when saving the xmpp configuration it shows following (but that's probably an other bug):
`{"reqId":"I2VfAm2UCLnLmB7v9AT9","level":3,"time":"2017-09-12T12:53:57+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"POST","url":"\/cloud\/index.php\/apps\/ojsxc\/settings\/admin","message":"preg_match() expects parameter 2 to be string, array given at \/var\/www\/html\/cloud\/apps\/ojsxc\/lib\/Controller\/SettingsController.php#325","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.78 Safari\/537.36","version":"12.0.2.0"}
`

When I click the link "Login without chat" I'm able to login.

I get the same behaviour in Firefox and Chromium.

**Comment by sualko** [comment]
Did you test your bosh setup with another bosh client, like pidgin? Can you [enable debugging](https://github.com/jsxc/jsxc/wiki/Debugging) and post the related XMPP stanzas?

**Comment by yennor** [comment]
Sorry, it took me a while to get back to it.
I tried it out with pidgin. But it also didn't work. I didn't managee to get any log output which seemed to state the problem.
At the end I've got it working by not using the reverse proxy, but by changing the prosody config to use:
cross_domain_bosh = true
it works like a charm :-)
