### ISSUE TITLE
Login issue 

### ISSUE THREAD

**Issue by idevwebs** [nextcloud/jsxc.nextcloud#72]
Hello. This chat app is great. Thank you for your contributions!

I'm having a strange login issue with jsxc 3.3.0 (internal) and NC 12.0.2.

Weird, on system with FF 54 I login and chat icon is there and chat works. On other system with FF 56 and same user, I log in to NC but there's no chat app icon or roster. If before login I click the text link to login without chat, after login I see the icon and roster list with relogin link, though modal does not log me in though.

FF 56 Console:

[WARN] No settings provided  jsxc.min.js:13:1885
Content Security Policy: Ignoring duplicate source 'unsafe-inline'  (unknown)
Content Security Policy: Couldn’t parse invalid host 'unsafe-inline'  (unknown)
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
window.controllers/Controllers is deprecated. Do not use it for UA detection.  merged.js:2165
State changed to INITIATING  jsxc.min.js:13:1885
State changed to PREVCONFOUND  jsxc.min.js:13:1885
check master  jsxc.min.js:13:1885
I am the slave.  jsxc.min.js:13:1885
UI State changed to INITIATING  jsxc.min.js:13:1885
TypeError: jsxc.xmpp.conn is null[Learn More]

>>> Modal login attempt: Authentication failed with the chat server. Maybe the password is wrong?

[WARN] No settings provided

Logging also has:

Error | PHP | preg_match()  expects parameter 2 to be string, array given at  /usr/local/www/nginx/nextcloud/apps/ojsxc/lib/Controller/SettingsController.php#325
-- | -- | --

**Comment by LEDfan** [comment]
@sualko 
```
preg_match() expects parameter 2 to be string, array given at /usr/local/www/nginx/nextcloud/apps/ojsxc/lib/Controller/SettingsController.php#325
```
The `\OCP\Util::getVersion()` returns an array with the version info, i.e. `[major, zero, minor, internal_patch]`, so this would fix the error:
```

	private function isPasswordConfirmationRequired()
	{
		$version = \OCP\Util::getVersion();

		// copied from owncloud/settings/ajax/installapp.php
		$lastConfirm = (int) \OC::$server->getSession()->get('last-password-confirm');

		return $version[0] >= 11 && $lastConfirm < (time() - 30 * 60 + 15);
	}
```

But I think this is not implemented in the JS of the admin settings, because I only get a `Error!` message and not asked for my password.

@idevwebs 

Do you have any nextcloud tabs open in the FF 56 browser? In your log output there is:
```
 I am the slave. jsxc.min.js:13:1885
```
which means that the Chat app should be loaded into another tab.

**Comment by sualko** [comment]
> But I think this is not implemented in the JS of the admin settings

It is implemented, but I am not sure why it isn't working for you. Can you open a new issue?
