### ISSUE TITLE
Minimize / hide chat sidebar

### ISSUE THREAD

**Issue by k9t9** [nextcloud/jsxc.nextcloud#74]
The chat sidebar needs an option to be minimized hidden or closed.
As far as i know - now the only possibility is to "login without chat" but if one is already logged in  with chat - a logout-login again is neccessary to close the sidebar...
This is especially true on mobile where the chat bar occupies 50% of the screen and effectively disables the possibility of working with anything else. Adding an item such as "hide chat" or "close chat" or "minimize" to the chat menu [at bottom of bar where settings is located ]would solve the issue.

**Comment by k9t9** [comment]
Ok.. I was just told there is a small chat icon that hides the chat sidebar. For some reason it did not rendered correctly on my device when i noticed this non-issue. Sorry -:)

**Comment by sualko** [comment]
There are multiple ways to minimize/close the sizebar:

- Use the chat icon
- Click/tap on the left border of the sidebar
- Select the `offline` status
