### ISSUE TITLE
Auto-scroll to new msg

### ISSUE THREAD

**Issue by jillian1701** [nextcloud/jsxc.nextcloud#76]
Hello. I have a persistent issue running the latest version of NextCloud (12.0.3) with JSXC in which the window does not automatically scroll to the newest message, or even the most recent un-read message. I'm pretty sure that in my previous version of OwnCloud it worked. I've only recently upgraded from OC to NC and noticed the change. The expected behavior would be to always display the most recent message. 

Can I enable this feature or help debug in any way?

**Comment by sualko** [comment]
I can't reproduce your issue. On my installation it's scrolling like expected. Please check your js console for errors. Which browser do you use?

**Comment by sualko** [comment]
Sorry for the delayed answer. Was `[UID]` a replacement from you?

**Comment by jillian1701** [comment]
Correct. One UID, for example, is ac46bd7f-4baf-4d5f-a5d0-1662c4da5215. Another is 6ec8b637-49c1-4b5b-bd06-a1db1b95a5d8. 

Some additional info, having just upgraded to FireFox Quantum, there is an additional, new messages:

XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 120:

**Comment by sualko** [comment]
I'm sorry that you encountered a new error, but without a location it's quite useless. If you reload the page do you see the new messages?

**Comment by jillian1701** [comment]
The new error appears with every new msg that does not scroll. I upgraded to 3.3.2 and both it still appear. I can only assume they are related, however I agree it's not much help without additional info. 

No one else has reported this issue of auto-scrolling? I have it on multiple system (WIN and LIN) using multiple browsers on each (FF and Chrome).  I wonder then it it's somehow my nextcloud or xmpp setup?

Could not load message with uid c4e89aea-1476-4b93-b3ec-668257c40f8d
jsxc.js:183:9
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 120:

**Comment by sualko** [comment]
Can you try to purge your local storage? Just open your js console and type `localStorage.clear()`.

**Comment by jillian1701** [comment]
Hi. I purged local storage and the issue persists, with the same errors. No change.

**Comment by sualko** [comment]
Which backend do you use?
