### ISSUE TITLE
'Send File' on Files Tab

### ISSUE THREAD

**Issue by jillian1701** [nextcloud/jsxc.nextcloud#77]
Hi. It appears there is a security issue with using the Send File feature when browsing files in the Files tab. If I attempt to send a file when in the files tab, I always receive the following error:

`Content Security Policy: The page’s settings blocked the loading of a resource at [resource name]`

However, the Send File feature works on any other tab; mail, news, announcements. 

Can I enable Send File within the Files tab?

Edit to clarify: NextCloud (12.0.3),  JSXC 3.3.1, using Firefox and Chrome on Linux and Windows.

**Comment by sualko** [comment]
Can you post your CSP of the specific site?

**Comment by jillian1701** [comment]
Hi. Thank you for responding. Below is the CSP output based on curl -I for various levels of my domain. I notice that the files app does not have a nonce-KEY. Also note these are the defaults; I have not changed them at all. 

/nextcloud/
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'nonce-KEY='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';

/nextcloud/index.php/apps/files/
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self' mysite.com upload.mysite.com;media-src 'self' blob:;child-src 'self'

nextcloud/index.php/apps/Rainloop/
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'nonce-KEY='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';

**Comment by sualko** [comment]
I guess your `[resource name]` points to a different host, than your nextcloud host. Just enter the host under "External services" in your jsxc admin page. If you are logged in you can also click on "Insert upload services automatically".

**Comment by jillian1701** [comment]
Hi. [resource name] is the same as my host name and I have entered them under external services. I think it might have something to do with the CSP settings for this particular page as I notice they're different from the other pages. 

It seems the defaul-src is set to 'none', which would prevent loading any resource, but clearly I can upload files in NextCloud, I just can't send them via jsxc. It seems that the files app is modifying the default CSP settings. 

I'm hesitant to modify the CPS policy for this page b/c I'm worried that may compromise the functions of uploading/sharing files themselves.
