### ISSUE TITLE
Please provide a feasible and updated installation documentation

### ISSUE THREAD

**Issue by fishfree** [nextcloud/jsxc.nextcloud#81]
Please provide a step-by-step installation manual for Ubuntu 16.04 or CentOS 7. The current one is out-of-date and confusing.

**Comment by MarcelWaldvogel** [comment]
You mean, along the lines of

> If your organisation is already running an XMPP server: Congratulations! Just add the parameters you got from your XMPP server admin.
> If not, follow the instructions here: https://github.com/jsxc/xmpp-cloud-auth/wiki

?

**Comment by fishfree** [comment]
@MarcelWaldvogel 
Thank you! But in your documentation, I have to install nextcloud from scratch. I need to integrate jsxc with a nextcloud server on production.

**Comment by MarcelWaldvogel** [comment]
The xmpp-cloud-auth wiki covers the novice admin, ready to install everything.

The [built-in documentation for xmpp-cloud-auth](https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Installation.md) covers the process of adding an XMPP server, using Nextcloud as the authentication source.

The experienced XMPP admin, which already has a setup should be able to fill in the fields in JSXC. Maybe together with hints from the web, including [this article](https://netfuture.ch/2017/09/modern-ejabberd-configuration/). But then, (s)he may have other requirements not covered there as well.

I think we already cover a wide spectrum, maybe not as well organized as I present it here, but we will change it. However, you seem to be missing your case. Can you describe it?

**Comment by fishfree** [comment]
@MarcelWaldvogel 
Thank you very much! I will try later.
