### ISSUE TITLE
Image preview with other xmpp clients

### ISSUE THREAD

**Issue by RabbitDuck** [nextcloud/jsxc.nextcloud#82]
Hi,

nextcloud 12.04 server and ejabberd-17.12.

Enabled the http_upload module in ejabberd and file upload and receive via http_upload both run normally. 

But image preview (thumbnail) only show if clients are using nextcloud jsxc.

The test cases are (all use http_upload method):
1) jsxc <-> jsxc = both show the thumbnail
2) jsxc  -> Conversations = jsxc shows thumbnail; Conversations shows the download URI
3) Conversations -> jsxc =  Conversations shows thumbnail; jsxc shows URI
4) jsxc -> Gajim = both show the thumbnail (Gajim installed the Url image preview plugin)
5) Gajim -> jsxc =  Gajim shows the thumbnail; jsxc shows the URI
6) Gajim <-> Conversations = both show the thumbnail correctly

Any ideas?
Thanks

**Comment by sualko** [comment]
We are aware of this limitation and fixed it already in the upcoming jsxc 4.0, see https://github.com/jsxc/jsxc/pull/581/commits/ba97c28d62c58809593ffdb6a860f0109f73360a. But anyway, thanks for taking the time to report an issue.
