### ISSUE TITLE
OMEMO support

### ISSUE THREAD

**Issue by runout-at** [nextcloud/jsxc.nextcloud#85]
OMEMO support was added to jsxc recently.
It would be great to have that in the nextcloud version too.

https://github.com/jsxc/jsxc/issues/228

**Comment by sualko** [comment]
On our roadmap.

**Comment by xekon** [comment]
Let me know if you need any testers :)

**Comment by tigre-bleu** [comment]
Do you have an estimated time for this feature?

**Comment by mwlczk** [comment]
Hi sualko, thx for your wokr.
Right now I cannot see any _refactoring_ branch or does it have a different name.

**Comment by Neustradamus** [comment]
Any news?

**Comment by sualko** [comment]
2 weeks ago we released our [first beta of JSXC 4.0](https://www.jsxc.org/blog/2019/03/02/v4.0.0-beta1-released.html) with OMEMO support. Probably by end of this week we will release another beta. If everything runs smooth we are hoping to release the final version by end of April. If you have time, please help testing.

**Comment by sualko** [comment]
We just released our [second beta of JSXC 4.0](https://github.com/nextcloud/jsxc.nextcloud/releases/tag/v4.0.0-beta.2). If you have time, please give it a try.

**Comment by mwlczk** [comment]
@sualko I am getting this error, when I log in to nextcloud with 4.0-beta2 enabled.
I unzipped the release-zip ontop of the old 3.4.3 realese and enabled JSXC.
I can configure JSXC in the settings section. But it wouldn't load as an app, as before:

Loading failed for the <script> with source “https://cloud.walczak.io/apps2/ojsxc/js/config.js?v=7d911443-8”. ojsxc:38:1

**Comment by MarcelWaldvogel** [comment]
Did you remove the old JSXC app folder first?

**Comment by sualko** [comment]
@mwlczk please open a new issue and fill the issue template. It would also be great if you could attach your htaccess file.

**Comment by Neustradamus** [comment]
In the same time: XEP-0384: OMEMO Encryption has been updated to 0.4.0:
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

**Comment by sualko** [comment]
I think we can close this for now, because OMEMO support will be added to the next release.

@Neustradamus I'm in the list of authors :wink: and therefore I know that's too early to implement it. There will be probably some more changes in the next few days/weeks.

**Comment by Neustradamus** [comment]
sualko: I know that you are one author ;)

**Comment by Neustradamus** [comment]
For information, after the 0.4.0, there is a 0.5.0.
- https://xmpp.org/extensions/xep-0384.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html
