### ISSUE TITLE
[PHP 7.2] count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Schmuuu** [nextcloud/jsxc.nextcloud#87]
### Steps to reproduce
1. Update PHP to version PHP 7.2.2
2. update jsxc chat app in Nextcloud app overview if necessary
3. look at the logs

### Expected behaviour
probably no error messages ;)

### Actual behaviour
the Nextcloud log is literally flooded. Within a few minutes there are **a lot** error messages of the kind:

{"reqId":"IXXXXhWXXXV","level":3,"time":"2018-02-07T15:17:34+01:00","remoteAddr":"XX.XXX.XX.XXX","user":"USER1","app":"PHP","method":"POST","url":"\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/nextcloud\/apps\/ojsxc\/lib\/newcontentcontainer.php#36","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"TXSXXXX3YCUXX0","level":3,"time":"2018-02-07T15:17:35+01:00","remoteAddr":"XX.XXX.XX.XXX","user":"USER2","app":"PHP","method":"POST","url":"\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/nextcloud\/apps\/ojsxc\/lib\/Controller\/HttpBindController.php#181","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}

## Server configuration detail

**Operating system:** Linux 4.14.17-1-lts #1 SMP Sat Feb 3 21:30:38 CET 2018 x86_64

**Webserver:** nginx/1.12.2 (fpm-fcgi)

**Database:** mysql 10.1.30

**PHP version:** 7.2.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, Phar, curl, exif, ftp, gd, gmp, intl, iconv, pdo_mysql, zip, apcu, memcache, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0.5 

**Where did you install Nextcloud from:** Web Updater

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.1.1
 - apporder: 0.4.1
 - audioplayer: 2.2.5
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - circles: 0.13.6
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.0.1
 - dav: 1.4.6
 - deck: 0.3.0
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_reader: 1.2.2
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.9
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ojsxc: 3.3.2
 - onlyoffice: 1.2.0
 - password_policy: 1.3.0
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.3
 - spreed: 3.0.1
 - systemtags: 1.3.0
 - telephoneprovider: 1.0.1
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - user_usage_report: 1.0.1
 - workflowengine: 1.3.0
Disabled:
 - checksum
 - drawio
 - encryption
 - impersonate
 - passman
 - sharerenamer
 - survey_client
 - tasks
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my.domain.tld",
        "192.xxx.xx.xx",
        "localhost"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "version": "13.0.0.14",
    "logtimezone": "Europe\/Berlin",
    "appstore.experimental.enabled": true,
    "appstoreenabled": true,
    "appstoreurl": "https:\/\/api.nextcloud.com\/v1",
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\TIFF"
    ],
    "filelocking.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "maintenance": false,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updater.release.channel": "stable",
    "loglevel": 2,
    "theme": "",
    "installed": true,
    "overwrite.cli.url": "https:\/\/my.domain.tld",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** Arch Linux 4.14.17

## Logs

<details><summary>Nextcloud log</summary>

```
{"reqId":"IXXXXhWXXXV","level":3,"time":"2018-02-07T15:17:34+01:00","remoteAddr":"XX.XXX.XX.XXX","user":"USER1","app":"PHP","method":"POST","url":"\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/nextcloud\/apps\/ojsxc\/lib\/newcontentcontainer.php#36","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"TXSXXXX3YCUXX0","level":3,"time":"2018-02-07T15:17:35+01:00","remoteAddr":"XX.XXX.XX.XXX","user":"USER2","app":"PHP","method":"POST","url":"\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/nextcloud\/apps\/ojsxc\/lib\/Controller\/HttpBindController.php#181","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
```
</details>

**Comment by sualko** [comment]
Thanks for the report. This is a result of one of the backward incompatible changes in 7.2, see [Warn when counting non-countable types](http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types).

I created a pr, but @LEDfan has to review it first.

**Comment by Schmuuu** [comment]
Awesome! Thanks for the quick reply and the attempt to fix this issue. Hopefully LEDfan finds the time for a review soon :)

If you need somebody to test the fix, I can offer my help of course. Just need to know how to apply the fix on my server without manually editing all changed files ;)

**Comment by sualko** [comment]
The pr was merged as 104cd914973b5c4884eecf6936b2a088eb403b62. To test those changes just replace your `ojsxc/lib` folder with the one from this repo.

**Comment by Schmuuu** [comment]
Hm :(
Sorry for being too stupid for this. I don't find a download button for the lib directory and downloading every single file from RAW view is taking much too long. 

When I download the repository at this point in the history (https://github.com/nextcloud/jsxc.nextcloud/tree/104cd914973b5c4884eecf6936b2a088eb403b62) and place the ojsxc folder under nextcloud/apps then I see complains in the nextcloud.log that many files in nextcloud/apps/ojsxc/js/jsxc/ are missing. This directory is actually empty. 

Could you please help me out here?

**Comment by sualko** [comment]
Sure. Just [download the entire repo as zip](https://github.com/nextcloud/jsxc.nextcloud/archive/master.zip) and just replace the `lib` folder.

**Comment by Schmuuu** [comment]
Thanks, that did it. Thought there was an even easier solution, where I can download this specific and fixed package :D 
Anyway, the error messages are gone, everything works fine now. Thanks a lot!
