### ISSUE TITLE
deleting an LDAP user takes several minutes when jsxc.nextcloud is active

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/jsxc.nextcloud#91]
jsxc.nextcloud: 3.3.2

## Expected behaviour

When I delete a user from LDAP which isn't in LDAP anymore with `occ user:delete <user>` it should only take a couple of seconds.

## Actual behaviour

When jsxc.nextcloud is active, deleting such a user takes several minutes.
These are the SQL queries that the SQL server is receiving during that time:
```
SELECT "appid", "configkey", "configvalue" FROM "oc_preferences" WHERE "userid" = $1
```
```
SELECT "ldap_dn" FROM "oc_ldap_user_mapping" WHERE "owncloud_name" = $1
```
```
INSERT INTO "oc_ojsxc_stanzas" ("to", "from", "stanza") VALUES($1,$2,$3)
```

It looks like although I am using an external XMPP server, JSXC is trying to [keep the rosters for its internal server up to date](https://github.com/nextcloud/jsxc.nextcloud/blob/a4fb2f87bff2d18f88838b3519d9d061215d1e2e/build/lib/rosterpush.php#L77-L91) after a [user removal](https://github.com/nextcloud/jsxc.nextcloud/blob/a4fb2f87bff2d18f88838b3519d9d061215d1e2e/build/lib/hooks.php#L79-L88).

As a result it took up to 9 minutes to delete a user from (an admittedly large) LDAP.

**Comment by sualko** [comment]
@LEDfan two questions:

- can we safely disable all hooks if the internal backend is not used?
- why is there a roster push for all users? It should be enough for users who are online.

**Comment by LEDfan** [comment]
@DanScharon thanks for reporting, it's a bit silly I didn't think of this earlier.

> can we safely disable all hooks if the internal backend is not used?

Yes :smiley: 

> why is there a roster push for all users? It should be enough for users who are online.

Because when a user is offline (i.e. there is no browser window open) the roster is still cached in the localStorage of users, when they open JSXC again the roster is loaded from localStorage.
