### ISSUE TITLE
nextcloud jsxc after enable, nextcloud load slow.

### ISSUE THREAD

**Issue by gurussia** [nextcloud/jsxc.nextcloud#92]
HI guys.

When nextcloud jsxc aplication is disabled, nextlcoud work inmediatelly. If you have fast internet, open your nextcloud and if it is configured normal it will load inmediatelly. Now when nextcloud jsxc application is enabled, nextcloud start work slow, include when messages are sendings it can wait 2 min. to be received or maybe 5 min. to send one simple text. So if you send simply . you have to wait 2 min. or 5 min. to this . to be received. We live in 21 century and one simpli . need to be delivered inmediatelly, this is not 3000 GB. you are sending, you are sending one simply .

This issue is not from php7.2, this issue is from nextcloud 11 or nextcloud 12, with php5. I didn't know how github was working, so im reporting. nextcloud jsxc has problems. I just remember when i try android clients and point to internal nextcloud, messages inmediatelly was sending and received. So nextcloud jsxc has to be problem from nextcloud.

In nextcloud log there is nothing strange, there was: 

Error	PHP	count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/apps/ojsxc/lib/newcontentcontainer.php#36	a few seconds ago
Error	PHP	count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/apps/ojsxc/lib/Controller/HttpBindController.php#181	a few seconds ago
Error	PHP	count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/apps/ojsxc/lib/newcontentcontainer.php#36

And there is another issue i open it in nextcloud server, with SMB but nextcloud server didn't comment what is issue.

**Comment by LEDfan** [comment]
Hi @gurussia. The error messages are solved in the master version.

Do you use the internal backend or an external XMPP server?

> I just remember when i try android clients and point to internal nextcloud, messages inmediatelly was sending and received. So nextcloud jsxc has to be problem from nextcloud.

What do you exactly mean with this? Are you using XMPP clients with Nextcloud, or the Android files app for Nextcloud (https://play.google.com/store/apps/details?id=com.nextcloud.client)?

There is a small performance improvement built into https://github.com/nextcloud/jsxc.nextcloud/pull/90, but that should barely be noticeable.

**Comment by gurussia** [comment]
HI guys.

Lets simple message. it use nextcloud latst stable version. For some strange reason xmpp from the first version it try use was working slow. Maybe from nextcloud 11.x, when xmppl nextcloud application is enabled, nextcloud start work slow. So if you have 1 gb. fibre internet or 300 mb. internet " 30 MB. reals becouse they lie, 300 mb. are 30 mb. download " and when xmpp client is enabled nextcloud server start load slow, if you open second navigation or if you try enter from other computer and etc. nextcloud works slow. It is like you use ISDN connection with 23 kb. ps " 2 kbps download " worse, you have to wait 2 min. or 5 min. to open nextcloud, and 2 min. or 5 min. to send how i say in the first message one simply . " dot " Yes one simply . " dot " it is like it is connecting with nasa. slow... Now when inmediatelly nextcloud xmpp application is disabled, inmediatelly nextcloud start load inmediatelly with 1GB. internet or 300 mb. " 30 MB. real download " inmediatelly load, but you don't have xmpp, xmpp is disabled for that works inmediatelly nextcloud. Now the other day when i write to nextlcoud server, they close issue if i remember and they comment they can't help this is nextcloud talk and nextcloud xmpp problems i just remember that maybe server use http2 or maybe there is missing php mod. So what are the correct php module and how it can be solved xmpp to work inmediatelly with http2. Http2 remember is more stable, reliable, more fast include php7.2 i test it inmediatelly load nextcloud. But in this case php7.2 in not issue. Now for some peoples works and for some peoples don't work. When i start install nextcloud i din';t know how git works and how to open issue, but this is serious matter, becouse we LIVE in 21 century and sending and reciving one simply . YES "dot" has to be inmediatelly delivered. No you are not sending 1 gb. data you are sending one simply . " dot " so how much kilobytes has one simply . "dot"  <0 kb. >1 mb... impossible one simply . "dot" be 1mb. what has one simple . "dot" to be 1mb. Im sure one simply . "dot" is under 1 mb. so if you send one simply . " dot " it has inmediatelly be received be in ISDN, like be in 1 gb. Russian internet siberian. Yes in siberia it is -62C " Yes minus 62C " and there internet 1 GB. internet speed open inmediatelly.

So be more simple: Nextcloud xmpp aplication include nextcloud talk application when one of them or two of them are enabled " Look carefully i say, one of them of two of them. This mean one of them or two of them " nextcloud load very slow. Worse than ISDN 20 century internet... piu pa... for some strange reason when how i say in the beggining of first message and in some middle of this message nextcloud talk or nextcloud xmpp make nextcloud slow when one of them or two of them are enabled. So how i say in the beggining of the first message and in the middle of this message. When it use nextcloud from version 11.x the issue was. So nextcloud has born in: 

11 | 2016-12-13 | 2018-05 | 11.0.7 (2018-01-24) | 11.0.8 (2018-03-14)
-- | -- | -- | -- | --

2016-12-13 so this bugs are from 1 year and more than 2 months. So how is that possible this issue are not repaired. Guys please don't break nextcloud. Do you know how much peoples you are helping to escape from illegal government. Much and every second this number arrise. Do you like government illegaly spy on you in the WC when you go to shit, do you like government illegaly spy on you when you make sex with someone and etc. Hey guys in america there is First Ammendent, Second Ammendent, Third Ammendent. In europe there is Constitution Law... so this law are broken from governments  becouse some one them are paranoic becouse they men spouce are seeking other person, they are paranoic becouse you didn't change your tire of the car, they are paranoic becouse today you buy book " how to make love with more than 3 persons " governments are paranoic for everything and for everybody. If julian assange is really hero, if this american soldier who america illegaly convert him in transgender when he help humankind look real treat that governments, if snowden is really what he comment and i we need urgent protection. Guys we need fully working stable nextcloud.There is things, the real true can't be jailed everyday much peoples will arise.

**Comment by MarcelWaldvogel** [comment]
We are running Nextcloud with XMPP enabled and use it daily. We are not aware of any slow-down during sync or in the web browser.

There is more code to be downloaded from the server when logging in (and a few requests made to update roster information), so this is somewhat slower, but the slowdown there is part of the deal.

We would appreciate more information from you:
- During which activities do you notice slowdown?
- Can you quantify it? (e.g., by measuring number of seconds)
- Can you describe your setup? (Platform, XMPP server used, …)
- Which issue are you referring to? (e.g., URL)

**Comment by gurussia** [comment]
marcel you are developer, this mean, if you notice slow down, you can go to code and repair it. There is peoples who are not developers so they don;t know why it happend.

Marcel: how i say activities is complete, full. This mean, when nextcloud xmpp applications is disabled nextlcoud server inmediatelly open, if you have fast internet. In this case internet is fast. So lets continue. When nextcloud xmpp application is enabled nextcloud server work slow.

Marcel: how i say in all messages: When xmpp is enabled it can take 2 min. to 5 min. only to send one simply . "dot" How i say this is not sending 1gb. data this is not connecting to italian government, it just send one simply . " dot " that is no more than < 1 kb.

Setup is normal: i ask morris what is correct php mods, maybe this is missing some mods include somewhere men write xmpp could cause problems with http2.

Marcel: read my messages: Xmpp nexcloud app only send, write and etc. messages, but with this slow, it has nextcloud xmpp has to be disabled. Include when nextcloud xmpp is enabled nextcloud server start load slow, slow like you are opening with ISDN internet line. marcel do you remember isdn what is PIU PAUU PIUU PAUUUU PIUUUUUU PIUUUUUU that send noise... but thjis is not case, becouse internet is fast. When xmpp nextcloud is disabled nextcloud return work fast, include less than 1 second nextcloud server open.

marcel if you are not aware of any slow-down this don't mean they dont exist.

**Comment by MarcelWaldvogel** [comment]
We have thousands of users who do not experience this slowdown. So we need some information on what is different in your setup. Without that, nobody will be able to find out the difference and we have to close this issue.
