### ISSUE TITLE
 ejabberd error: extauth script has exitted abruptly with reason 'normalublicated but from 2 years and 2 months there is no solution. but jsxc module was updated maybe yestaday or other day and this issue continue persist extauth script has exitted abruptly with reason 'normalublicated but from inhuman.

### ISSUE THREAD

**Issue by gurussia** [nextcloud/jsxc.nextcloud#93]
Following from here: https://github.com/jsxc/xmpp-cloud-auth
how to enable xmpp to external xmpp server, becouse nextcloud server for some reason works slow, include messages are not inmediatelly received. I just remember. IN the past it configured xmpp server and nextcloud working, it don;t remember if messages has to be wait 2 min, or 5 min. to be delivered but when external xmpp server was configured it try from android xmpp client and send to another android client and messages inmediatelly had been received, inmediatelly is inmediatelly, you only write . " dot " and inmediatelly is received. it don;t remember if it had try from nextcloud to android messages or from android to android client messages. But messages was worked inmediatelly. Or maybe from nextcloud to android\.... it don't remember. So

Today it return try install ejabberd but something strange happend: Followed this how from the beggining of the message. it is unknown what happend.

On the XMPP server: For ejabberd installations

apt install ejabberd git python-bcrypt
cd /opt
git clone https://github.com/jsxc/xmpp-cloud-auth

but here it comment: https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Installation.md

Download the latest release and put it to your desired location (e.g. /opt/xmpp-cloud-auth) or clone this repository to remain on the leading edge:

cd /opt
sudo git clone https://github.com/jsxc/xmpp-cloud-auth

Create the xcauth user and directories:

sudo ./install.sh

Install Python and all desired libraries.

sudo apt install python python-requests python-configargparse python-bcrypt

So it is neccesary to install in xmpp-cloud-auth/install.sh or not. Becouse in the continued of the comments on this web page it don't comment nothing: https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd include on the next page: https://github.com/jsxc/xmpp-cloud-auth/wiki/nextcloud include on the next page: https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd-extauth

now it only comment /etc/xcauth.conf but in here it comment: https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Installation.md install Create the xcauth user and directories:

sudo ./install.sh

So is it neccesary to be installed or not. Becouse in https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd-extauth it has xcauth. So why it comment in the https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Installation.md when here it is installed https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd-extauth

Someone comment what is the correct way this to be installed https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd-extauth  In the past it make it works but it was much time and it was forget how to be solved. some comment what is correct order and i will make Real how-to becouse im sure there is more peoples who are lost in the reading and don't want to wastey life time. In internet everyrhing is bad explained, include there will be women who will try lie you, make this, buy this and you will build car...

Car can be build correctly with the men from men, commenting true. Include ejabberd has bosh but here it comment: https://github.com/jsxc/xmpp-cloud-auth/ comment http-bind But someone in internet they comment http-bind and bosh module are different, so someone comment correctly and if i have time and if i remember i will make true how to.

Becouse in the moment it comment this: https://github.com/jsxc/jsxc/issues/254 

This is from issue is more than 2 years and 2 months old, so there is no solution .

**Comment by MarcelWaldvogel** [comment]
Issue jsxc/jsxc#254 was due to [wrong permissions set by owncloud](https://github.com/jsxc/jsxc/issues/254#issuecomment-170894618). As soon as the user fixed it, by carefully following the instructions, it disappeared. If you have the same error message, that may be caused by something very different.

What do the logs say? Can you run it manually?

Based on your statement, I do not know what *you* actually did and what you only *copied* from our instructions. Our instructions are (right now) targeted at experienced Linux admins. We are happy if someone makes it more accessible. Tomorrow, we are holding a workshop where the attendees can set up a machine under our guidance, but unfortunately it is fully booked (and probably not close to you, anyway).

I will update the title, which I do not understand as it is now and is too long. Please explain more of your setup in the comment.

**Comment by gurussia** [comment]
https://github.com/nextcloud/jsxc.nextcloud/issues/93

This user has three files in his directory and it only have one, the one file is comming from you, xauth.. or something like that.

Lets try. I help friend make his nextcloud fully work with xmpp nextcloud xmpp " becouse nextcloud has bug when xmpp client app is enabled it work slow  but this is for nextcloud server "

So i re-read more than 6 times your manual about how to install nextcloud auth... and it is the same error: extauth script has exitted abruptly with reason

I'm writing becouse in the moment i have free time and my friend is playing footbal. So neither i neither today my friend, neither he friend could'nt understand your manual.

WHat has be doing to arrive in this issue git.

1. https://github.com/jsxc/jsxc and there i found there is authentication for nextcloud. We say great...

2. i go to ejabberd directory in the server: cd /var/magazin/html/ejabberd
 great it is directory: 
pwd
/var/magazin/html/ejabberd

Now git clone https://github.com/jsxc/xmpp-cloud-auth
git clone succesfully download. NOw this is that:

/var/magazin/html/ejabberd/xmpp-cloud-auth

ls -lah 

```
-rw-r--r-- 1 www-data www-data 4.2K Feb 23 05:09 CHANGELOG.md
drwxr-xr-x 2 www-data www-data 4.0K Feb 23 05:09 doc
drwxr-xr-x 8 www-data www-data 4.0K Feb 23 05:09 .git
-rw-r--r-- 1 www-data www-data   26 Feb 23 05:09 .gitignore
-rwxr-xr-x 1 www-data www-data  407 Feb 23 05:09 install.sh
-rw-r--r-- 1 www-data www-data 1.1K Feb 23 05:09 LICENSE
drwxr-xr-x 2 www-data www-data 4.0K Feb 23 05:09 prosody-modules
-rw-r--r-- 1 www-data www-data  846 Feb 23 05:09 README.md
drwxr-xr-x 2 www-data www-data 4.0K Feb 23 05:09 systemd
drwxr-xr-x 2 www-data www-data 4.0K Feb 23 05:09 tests
-rw-r--r-- 1 www-data www-data  270 Feb 23 05:09 .travis.yml
-rw------- 1 ejabberd ejabberd 2.9K Feb 23 05:12 xcauth.conf
-rwxr-xr-x 1 www-data www-data  556 Feb 23 05:09 xcauth.py
-rwxr-xr-x 1 www-data www-data  100 Feb 23 05:09 xcauth.sh
-rwxr-xr-x 1 www-data www-data  480 Feb 23 05:09 xcdbm.py
drwxr-xr-x 3 www-data www-data 4.0K Feb 23 05:09 xclib

```

Now unknown is: marcel in your manual you comment: When using xmpp-cloud-auth.py

Where is xmpp-cloud-auth.py I seek for this xmpp-cloud-auth.py and it is not in the directory. In this user https://github.com/nextcloud/jsxc.nextcloud/issues/93 he has three files. So i continue... i paste ejabberd.yaml or .yalm in the moment i dont remember. 

ls -lah /etc/xcauth.conf 
-rw------- 1 ejabberd ejabberd 2.9K Feb 23 05:12 /etc/xcauth.conf

After that it go to cd /var/magazin/html/ejabberd/
now it start ejaberdctl: ./bin/ejaberdctl start

and now it comment: extauth script has exitted abruptly with reason. Include second issue is that this error is seconds continue: extauth script has exitted abruptly with reason, less than seconds extauth script has exitted abruptly with reason and etc. less than seconds extauth script has exitted abruptly with reason...

until user stop ejabberd. So this arrive becouse manual is improper or obsolete. in your manual you comment: xmpp-cloud-auth.py but there is no xmpp-cloud-auth.py

In user https://github.com/nextcloud/jsxc.nextcloud/issues/93
it comment there are three files, in after git clone your repo it don't have xmpp-cloud-auth.py


Now i can make 100 % correct manual, but i work with humankinds. Only with real things that works. So if you really want to manual, you need to co-operate with me 100 % and comment me everything that is neccesary jsxc autentication work with nextcloud. So in the moment for this issue it has 6 chrome windows opens, so this is inhuman to have 6 windows chrome open.

**Comment by gurussia** [comment]
Now if someone ask why he don't understand my text i too don't understand text, becouse there is misunderstanding in the manual, it is like you are in shit. 

Now for humankind manual:

It is neccesary:

All real files that works, updated not obsoleted. in ejuabberd.yalm too becouse i try your ejabberd.yaml and it comment error.

**Comment by MarcelWaldvogel** [comment]
What is in `/etc/xcauth.conf` (please anonymise the secrets)?

What happens when you run `./xcauth.py` manually in that directory?

What happens if you run `./xcauth.py -I username domainname`, where *username* is a valid username and *domainname* the name of your domain?

What XMPP server are you running? 

If you are running *Prosody*, did you include the fix from the `./prosody-modules/` directory according to the information in `./doc/` (this is mentioned in `README.md`)?
