### ISSUE TITLE
what of this two is correct for nextcloud:

### ISSUE THREAD

**Issue by gurussia** [nextcloud/jsxc.nextcloud#94]
What....

guys make jsxc in one github webpage in the moment i see jsxc has exactly 

1. https://github.com/jsxc/jsxc and this 
2. https://github.com/nextcloud/jsxc.nextcloud

So what is correct for jsxc nextcloud to work with ejabberd.

**Comment by MarcelWaldvogel** [comment]
JSXC is a JavaScript XMPP library, at the first location. JSXC.Nextcloud is a Nextcloud app which uses this library; other plugins for other web applications do exist (and existed prior to JSXC.Nextcloud). So this is all correct as it is. See https://jsxc.org/

**Comment by gurussia** [comment]
no understand. So nextcloud xmpp client to work with nextcloud server what is neccesary.

Now if nextcloud xmpp to connect with other xmpp server " not internal xmpp server of nextcloud " what is neccesary.

marcel i don';t care other library/. In the moment i only want to know. Why there are two link to jsxc. It is lost becouse there is peoples who bad comment. So marcel, to nextcloud xmpp application to work, what manual has to comment.

**Comment by gurussia** [comment]
what it want is. xmpp with nextcloud clients, no nextcloud clients and voip " voice over ip and video over ip "

**Comment by MarcelWaldvogel** [comment]
The internal server and the managed server seem to work perfectly for thousands of users. Only a few clicks required.

If that does not work for you and you cannot give any information with the necessary structure and technical depth, I am sorry. Then also setting up an XMPP server is not for you.

**Comment by gurussia** [comment]
marcel Then also setting up an XMPP server is not for you.

If peoples like you marcel comment bad, obsolete manual and etc. peoples will can't make it work.

So this is not neccesarry information. marcel now suppose person pass with bad explanations, manual missunderstanding, obsolete manuals and etc. so marcel how to do think why this person need to make manuals for other peoples when peoples are non-gratos, marcel you are wrong, if you see injustice and you don't compliant it with justice and police, when 10 peoples happend the same, and 11 person fill complaint with justice system and police i assure the judge will tell him. Why you complaint about this crime, when 10 peoples didn't complaint. so marcel remember never put person in general. marcel when i install nextcloud 11 xmpp didn't work either, so i didn't know how github was working and i didn't want to try lost time to write with other peoples. So... marcel if you don't belive look in twitter: MEETOOMEN " mee too men " So every person can get his conclusions. nextcloud is good, but nextcloud talk and nextcloud xmpp client are dissapointent. In the moment i'm complaining, but days are comming more peoples will come complaint about nextcloud talk and nextcloud xmpp.
