### ISSUE TITLE
[BUG] Login without Chat Remains - Minor

### ISSUE THREAD

**Issue by c0fe** [nextcloud/jsxc.nextcloud#97]
### Steps to reproduce
1. Install Nextcloud Talk chat app via browser and as admin
2. Remove Nextcloud Talk chat app
3. Logout

### Expected behaviour
The link "Login without chat" should be removed after Nextcloud Chat is removed

### Actual behaviour
Link remains

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
NGiNX 1.10.3
**Database:**
10.2.x
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
zip
**Browser**
Chrome 64.0.3282.186 (latest as of posting). I also did clear cache and everything in the browser.
**Screenshot**
https://i.imgur.com/sMmveoj.png

**Comment by sualko** [comment]
If the link remains, you didn't remove ojsxc. Just delete the folder in `apps/ojsxc`.

**Comment by MarcelWaldvogel** [comment]
You mean: Remove JSXC?

**Comment by c0fe** [comment]
@sualko i did think on this but it is not in there.
