### ISSUE TITLE
Disable OTR in admin area

### ISSUE THREAD

**Issue by zuglufttier** [nextcloud/jsxc.nextcloud#99]
Hi,

I'd like to disable OTR in jsxc in order to not confuse my users. I'll confuse them enough once OMEMO arrives ;)

Is it possible to do that right now?

**Comment by sualko** [comment]
I'm sorry, but there is no UI switch to do that, but you can edit it directly at [ojsxc.js#L356](https://github.com/nextcloud/jsxc.nextcloud/blob/master/js/ojsxc.js#L356) like this: 

```
...
app_name: 'Nextcloud',
otr: {enable: false},
loginForm: {
...
```

**Comment by ASmith-** [comment]
otr: {enable: false} is not found whatsoever on the entire paged file referred to here https://github.com/nextcloud/jsxc.nextcloud/blob/master/js/ojsxc.js#L356 much less on line 356. Its perhaps the wrong filename was listed and then somehow referenced for users to refer to on this?

**Comment by sualko** [comment]
@ASmith- you have to add it there. For example between `app_name` and `loginForm`.

**Comment by mw80** [comment]
I am also interested in disabling otr. Unfortunately I can't find the js file. Could you give an advice?

**Comment by sualko** [comment]
@mw80 if you are using 3.x it should be in `ojsxc/js/ojsxc.js`.

**Comment by mw80** [comment]
I am using already 4.0.0-rc.1.
